=== arielmbomakaeyros/como-files/Flow_Decomposition_Schema_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/Flow_Decomposition_Schema",
    "title": "flowComponentList",
    "type": "object",
    "description": "Main result from the flow decomposition",
    "properties": {
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "id": {
            "description": "Unique identifier of the flow decomposition result",
            "type": "string"
        },
        "selectedXnecResultId": {
            "description": "Reference to the related unique identifier of the XNEC selection result (selected XNEC set)",
            "type": "string"
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/timeHorizonCodelist"
        },
        "xnecList": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/xnecFlowComponent"
            }
        }
    },
    "definitions": {
        "ValueFlowComponentType": {
            "description": "The code list of the flow component types",
            "type": "string",
            "enum": [
                "allocatedFlow",
                "internalFlow",
                "loopFlow",
                "loopFlowOutsideCore",
                "pstFlow"
            ]
        },
        "componentFlow": {
            "type": "object",
            "properties": {
                "biddingZoneList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/distributedFlow"
                    }
                },
                "componentType": {
                    "description": "Type of the related flow component (according to the code list)",
                    "$ref": "#/definitions/ValueFlowComponentType"
                },
                "value": {
                    "description": "The value of the related network element’s flow [MW]",
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "componentType",
                "value"
            ]
        },
        "distributedFlow": {
            "type": "object",
            "properties": {
                "biddingZoneCode": {
                    "description": "EIC code of the bidding zone",
                    "type": "string"
                },
                "value": {
                    "description": "The value of the related network element’s flow per bidding zone [MW]",
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "biddingZoneCode",
                "value"
            ]
        },
        "timeHorizonCodelist": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "xnecFlowComponent": {
            "type": "object",
            "description": "Flow components for the selected XNEC",
            "properties": {
                "adjustedFmax": {
                    "description": "Adjusted active power flow max to AC load flow results [MW]",
                    "type": "number"
                },
                "componentList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/componentFlow"
                    }
                },
                "convertedXnecId": {
                    "description": "Reference to unique identifier of the converted XNEC",
                    "type": "string"
                },
                "totalFlow": {
                    "description": "Active power flow that is considered as the reference for the decomposition [MW]",
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "adjustedFmax",
                "convertedXnecId",
                "totalFlow"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "businessDay",
        "businessTimestamp",
        "crosaVersion",
        "csProcessVersion",
        "id",
        "selectedXnecResultId",
        "timeHorizon"
    ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_7.json
{
    "businessDay": "2024-07-11",
    "businessTimestamp": "2024-07-11T01:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "c066ddf4dcd65cb3e8b66911",
    "selectedXnecResultId": "c21893330962af9db013e568",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 84.33,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": -0.41,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.62
                        },
                        {
                            "biddingZoneCode": "10YFR-RTE------C",
                            "value": 0.21
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": -0.45,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.62
                        },
                        {
                            "biddingZoneCode": "10YFR-RTE------C",
                            "value": 0.17
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": -0.56,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.68
                        },
                        {
                            "biddingZoneCode": "10YFR-RTE------C",
                            "value": 0.12
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": -0.13,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.62
                        },
                        {
                            "biddingZoneCode": "10YFR-RTE------C",
                            "value": 0.49
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": -0.08,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.58
                        },
                        {
                            "biddingZoneCode": "10YFR-RTE------C",
                            "value": 0.5
                        }
                    ]
                }
            ],
            "convertedXnecId": "79c81adac4bc1c129855a0c2",
            "totalFlow": 86.93
        }
    ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_2.json
{
    "businessDay": "2024-06-13",
    "businessTimestamp": "2024-06-13T01:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "cb90a7d0c3e1bde21a7b46e4",
    "selectedXnecResultId": "c768fce67d1c1008c79bdb18",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 99.63,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": 0.58,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.21
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A75E",
                            "value": 0.79
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": 0.47,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.26
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A75E",
                            "value": 0.73
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": 0.16,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.3
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A75E",
                            "value": 0.46
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": 0.33,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.23
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A75E",
                            "value": 0.56
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": 0.29,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A74G",
                            "value": -0.25
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A75E",
                            "value": 0.54
                        }
                    ]
                }
            ],
            "convertedXnecId": "f17a69f61db47a0e7c1fe754",
            "totalFlow": 27.0
        }
    ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_10.json
{
    "businessDay": "2024-04-12",
    "businessTimestamp": "2024-04-12T01:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "12d4d7d5f7b113ca49c7a506",
    "selectedXnecResultId": "5611f6d8b74e7baa091b5a45",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 70.98,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": 0.06,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.3
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.08
                        },
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": -0.32
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": 0.04,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.31
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.05
                        },
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": -0.32
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": -0.23,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.24
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.02
                        },
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": -0.49
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": 0.11,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.27
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.04
                        },
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": -0.2
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": -0.02,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.26
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A885",
                            "value": 0.07
                        },
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": -0.35
                        }
                    ]
                }
            ],
            "convertedXnecId": "212b3eb7213d692472d0d23c",
            "totalFlow": 29.01
        }
    ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_9.json
{
    "businessDay": "2024-03-11",
    "businessTimestamp": "2024-03-11T01:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "2ca9d27e6c570193257bf1c3",
    "selectedXnecResultId": "076d497f6093c392c9a92133",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 3.53,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": -0.38,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A46L",
                            "value": 0.4
                        },
                        {
                            "biddingZoneCode": "10YCA-BULGARIA-R",
                            "value": -0.78
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": -0.22,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A46L",
                            "value": 0.4
                        },
                        {
                            "biddingZoneCode": "10YCA-BULGARIA-R",
                            "value": -0.62
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": -0.65,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A46L",
                            "value": 0.32
                        },
                        {
                            "biddingZoneCode": "10YCA-BULGARIA-R",
                            "value": -0.97
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": -0.33,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A46L",
                            "value": 0.41
                        },
                        {
                            "biddingZoneCode": "10YCA-BULGARIA-R",
                            "value": -0.74
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": -0.21,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10Y1001A1001A46L",
                            "value": 0.4
                        },
                        {
                            "biddingZoneCode": "10YCA-BULGARIA-R",
                            "value": -0.61
                        }
                    ]
                }
            ],
            "convertedXnecId": "0261fad8dacf76a22eb79d47",
            "totalFlow": 17.06
        }
    ]
}

=== arielmbomakaeyros/como-files/como_json_schemas/Flow_Decomposition_fixed_file_1_old_sample.json
{
  "businessDay": "2024-09-20",
  "businessTimestamp": "2024-09-20T17:39:06.828160",
  "crosaVersion": 1,
  "csProcessVersion": 1,
  "id": "0cd89406-aaba-4241-bb0a-3f6503544be8",
  "selectedXnecResultId": "05d19ae8-8f68-4d2c-936e-22c14c9c60c4",
  "timeHorizon": "twoDaysAhead",
  "xnecList": [
    {
      "adjustedFmax": 185.87,
      "componentList": [
        {
          "componentType": "allocatedFlow",
          "value": 0.61,
          "biddingZoneList": [
            {
              "biddingZoneCode": "10YIE-1001A00010",
              "value": 0.61
            },
            {
              "biddingZoneCode": "10YNL----------L",
              "value": 0.61
            },
            {
              "biddingZoneCode": "10Y1001A1001A48H",
              "value": 0.61
            }
          ]
        },
        {
          "componentType": "internalFlow",
          "value": 0.92,
          "biddingZoneList": [
            {
              "biddingZoneCode": "10YIE-1001A00010",
              "value": 0.92
            },
            {
              "biddingZoneCode": "10YNL----------L",
              "value": 0.92
            },
            {
              "biddingZoneCode": "10Y1001A1001A48H",
              "value": 0.92
            }
          ]
        },
        {
          "componentType": "loopFlow",
          "value": -0.32,
          "biddingZoneList": [
            {
              "biddingZoneCode": "10YIE-1001A00010",
              "value": -0.85
            },
            {
              "biddingZoneCode": "10YNL----------L",
              "value": 0.24
            },
            {
              "biddingZoneCode": "10Y1001A1001A48H",
              "value": 0.29
            }
          ]
        },
        {
          "componentType": "loopFlowOutsideCore",
          "value": -0.9,
          "biddingZoneList": [
            {
              "biddingZoneCode": "10YIE-1001A00010",
              "value": -0.9
            },
            {
              "biddingZoneCode": "10YNL----------L",
              "value": -0.9
            },
            {
              "biddingZoneCode": "10Y1001A1001A48H",
              "value": -0.9
            }
          ]
        },
        {
          "componentType": "pstFlow",
          "value": 0.6,
          "biddingZoneList": [
            {
              "biddingZoneCode": "10YIE-1001A00010",
              "value": 0.6
            },
            {
              "biddingZoneCode": "10YNL----------L",
              "value": 0.6
            },
            {
              "biddingZoneCode": "10Y1001A1001A48H",
              "value": 0.6
            }
          ]
        }
      ],
      "convertedXnecId": "9d7ce300-0da8-4930-9b2e-d38931aea46e",
      "totalFlow": 86.19
    }
  ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_5.json
{
    "businessDay": "2023-11-05",
    "businessTimestamp": "2023-11-05T02:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "99ac106fe1d073096582c84a",
    "selectedXnecResultId": "9cdf615fdfd4ab514fa81913",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 43.36,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": 1.36,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YPT-REN------W",
                            "value": 0.45
                        },
                        {
                            "biddingZoneCode": "10YFI-1--------U",
                            "value": 0.91
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": 1.33,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YPT-REN------W",
                            "value": 0.45
                        },
                        {
                            "biddingZoneCode": "10YFI-1--------U",
                            "value": 0.88
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": 0.95,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YPT-REN------W",
                            "value": 0.44
                        },
                        {
                            "biddingZoneCode": "10YFI-1--------U",
                            "value": 0.51
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": 1.32,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YPT-REN------W",
                            "value": 0.54
                        },
                        {
                            "biddingZoneCode": "10YFI-1--------U",
                            "value": 0.78
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": 1.39,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YPT-REN------W",
                            "value": 0.51
                        },
                        {
                            "biddingZoneCode": "10YFI-1--------U",
                            "value": 0.88
                        }
                    ]
                }
            ],
            "convertedXnecId": "3ff90fe3076fe53dd66393c4",
            "totalFlow": 10.97
        }
    ]
}

=== arielmbomakaeyros/como-files/Flow_Decomposition_test_data/Flow_Decomposition_file_8.json
{
    "businessDay": "2024-10-08",
    "businessTimestamp": "2024-10-08T02:30:00Z",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "a0b48c24bc715a0bc0d86e7a",
    "selectedXnecResultId": "57ff2a6a4dfcaa56c30a37c8",
    "timeHorizon": "dayAhead",
    "xnecList": [
        {
            "adjustedFmax": 60.59,
            "componentList": [
                {
                    "componentType": "allocatedFlow",
                    "value": -0.1,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": 0.61
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A45N",
                            "value": -0.71
                        }
                    ]
                },
                {
                    "componentType": "internalFlow",
                    "value": 0.13,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": 0.56
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A45N",
                            "value": -0.43
                        }
                    ]
                },
                {
                    "componentType": "loopFlow",
                    "value": -0.33,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": 0.52
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A45N",
                            "value": -0.85
                        }
                    ]
                },
                {
                    "componentType": "loopFlowOutsideCore",
                    "value": -0.14,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": 0.56
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A45N",
                            "value": -0.7
                        }
                    ]
                },
                {
                    "componentType": "pstFlow",
                    "value": -0.18,
                    "biddingZoneList": [
                        {
                            "biddingZoneCode": "10YRO-TEL------P",
                            "value": 0.58
                        },
                        {
                            "biddingZoneCode": "10Y1001A1001A45N",
                            "value": -0.76
                        }
                    ]
                }
            ],
            "convertedXnecId": "ae87075ef95a3f6538d24a64",
            "totalFlow": 88.32
        }
    ]
}
