=== arielmbomakaeyros/como-files/SelectedXnecResult_Scheme_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/SelectedXnecResult_Scheme",
    "title": "selectedXnecResult",
    "type": "object",
    "description": "XNEC selection result - selected XNECs",
    "properties": {
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "convertedXnecList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/convertedXnec"
            }
        },
        "crosaProcessType": {
            "type": "string"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "id": {
            "description": "Unique identifier of the selected result set",
            "type": "string"
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "xnecSelectionInputId": {
            "description": "Reference to unique identifier of the related XNEC selection input data set",
            "type": "string"
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_SELECTED_XNEC_RESULT"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "convertedXnec": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier of the converted XNEC (a combination of original XNEC(s) for the related contingency)",
                    "type": "string"
                },
                "originalXnec1": {
                    "description": "First original XNEC's data",
                    "$ref": "#/definitions/originalXnecData"
                },
                "originalXnec2": {
                    "description": "Second original XNEC's data",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/originalXnecData"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "id",
                "originalXnec1"
            ]
        },
        "originalXnecData": {
            "type": "object",
            "properties": {
                "assessedElementMrid": {
                    "description": "Mrid of the assessed element from assessed element (flat) list.",
                    "type": "string"
                },
                "assessedElementName": {
                    "description": "Name of the assessed element from the assessed element flat list.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "biddingZoneCode": {
                    "description": "EIC code of the bidding zone",
                    "type": "string"
                },
                "conductingEquipmentMrid": {
                    "description": "Mrid of the conducting equipment from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "contingencyMrid": {
                    "description": "Mrid of the related contingency",
                    "type": "string"
                },
                "contingencyName": {
                    "description": "Name of the contingency",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "fAfter": {
                    "type": "number"
                },
                "fBefore": {
                    "description": "Current on XNEC before RAO [A]",
                    "type": "number"
                },
                "fMax": {
                    "type": "number"
                },
                "hasCostlyRa": {
                    "description": "Indication whether the related costly remedial action was materialized for the XNEC (true) or not (false)",
                    "type": "boolean"
                },
                "iAfter": {
                    "description": "Current on XNEC after RAC, including agreed XRAs impact [A]",
                    "type": "number"
                },
                "iBefore": {
                    "type": "number"
                },
                "iMax": {
                    "description": "Maximum current on XNEC [A]",
                    "type": "number"
                },
                "id": {
                    "description": "Unique identifier of the original XNEC",
                    "type": "string"
                },
                "raMrid": {
                    "description": "Mrid of the related costly RA",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "tsoCode": {
                    "description": "EIC of the related TSO",
                    "type": "string"
                },
                "xneMrid": {
                    "description": "Mrid of the XNE from the CGM",
                    "type": "string"
                },
                "xneName": {
                    "description": "Name of the XNE from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "assessedElementMrid",
                "biddingZoneCode",
                "contingencyMrid",
                "fAfter",
                "fBefore",
                "fMax",
                "hasCostlyRa",
                "iAfter",
                "iBefore",
                "iMax",
                "id",
                "tsoCode",
                "xneMrid"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaProcessType",
        "crosaVersion",
        "csProcessVersion",
        "id",
        "timeHorizon",
        "xnecSelectionInputId"
    ]
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_9.json
{
    "businessDay": "2024-06-09",
    "businessTimestamp": "2024-06-09T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "55ac72d42e7ec500883852ba",
            "originalXnec1": {
                "assessedElementMrid": "602ba80066bf58a85c6d7bed",
                "assessedElementName": "976b30bfb1eb57c37824b28e",
                "biddingZoneCode": "91d08e65f76b5f958fe08fb3",
                "conductingEquipmentMrid": "df9fa122f1e48a7d981ec4cf",
                "contingencyMrid": "e8ad5c346e3b24e755cfbbe5",
                "contingencyName": null,
                "fAfter": 94.81,
                "fBefore": 15.89,
                "fMax": 36.2,
                "hasCostlyRa": true,
                "iAfter": 59.88,
                "iBefore": 87.76,
                "iMax": 14.59,
                "id": "d160b5562507ddede0fd9a17",
                "raMrid": "a390948b32f127c020d77933",
                "tsoCode": "f595131264cffcd84e500d1f",
                "xneMrid": "59b62499588c13a44bc4b855",
                "xneName": "c052528594b4c005577d4f5b"
            },
            "originalXnec2": {
                "assessedElementMrid": "ee48ca9f0c33abb3f62143bb",
                "assessedElementName": "56e39e75a2e90ebde28fab8c",
                "biddingZoneCode": "ff5985a7ec392af31ee7f147",
                "conductingEquipmentMrid": "89e4d7264ea840d1f442e7f6",
                "contingencyMrid": "b1ace352de32590d84a2b350",
                "contingencyName": null,
                "fAfter": 62.98,
                "fBefore": 48.92,
                "fMax": 33.39,
                "hasCostlyRa": true,
                "iAfter": 16.31,
                "iBefore": 60.42,
                "iMax": 77.68,
                "id": "db13a9b4e92f161e69bad41a",
                "raMrid": "0cc9389a2ab0793321a15b62",
                "tsoCode": "eea6ca25607cbf3c4d52d510",
                "xneMrid": "b896e107e35985a879486e5b",
                "xneName": null
            }
        }
    ],
    "crosaProcessType": "c1f82e8d5973d21fce0656cf",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "5a072c0b9ce831a27827bd2f",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "d2276bc8e183d016f328e7bb"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_6.json
{
    "businessDay": "2024-07-29",
    "businessTimestamp": "2024-07-29T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "2e8d458dcf010e283c3e08ae",
            "originalXnec1": {
                "assessedElementMrid": "efdf2a11834e299de1809557",
                "assessedElementName": "60d3a4c6258b946b910a7018",
                "biddingZoneCode": "10YAT-APG------L",
                "conductingEquipmentMrid": "91f2f44758f9fa803532a8f5",
                "contingencyMrid": "6d1d849fbf81631a93765ac3",
                "contingencyName": "0de5d957545abd3ec29c698a",
                "fAfter": 67,
                "fBefore": 73,
                "fMax": 71,
                "hasCostlyRa": false,
                "iAfter": 46,
                "iBefore": 69,
                "iMax": 53,
                "id": "50df48d710dbbf5cb94098a8",
                "raMrid": "a6f372943285c175adb9e23b",
                "tsoCode": "10XAT-APG------Z",
                "xneMrid": "efdf2a11834e299de1809557",
                "xneName": "60d3a4c6258b946b910a7018"
            },
            "originalXnec2": {
                "assessedElementMrid": "915c3d7de5ffad06f89367be",
                "assessedElementName": "cd5ff5b088e4f3483ec2ee13",
                "biddingZoneCode": "10Y1001A1001A82H",
                "conductingEquipmentMrid": "900f200c88b3364c4642c50c",
                "contingencyMrid": "6d1d849fbf81631a93765ac3",
                "contingencyName": "0de5d957545abd3ec29c698a",
                "fAfter": 67,
                "fBefore": 73,
                "fMax": 71,
                "hasCostlyRa": false,
                "iAfter": 46,
                "iBefore": 69,
                "iMax": 53,
                "id": "25f5fbc2d0a7dcc851c147f6",
                "raMrid": "a6f372943285c175adb9e23b",
                "tsoCode": "10XDE-EON-NETZ-C",
                "xneMrid": "915c3d7de5ffad06f89367be",
                "xneName": "cd5ff5b088e4f3483ec2ee13"
            }
        }
    ],
    "crosaProcessType": "cd9781b805ea2ab528b6dee2",
    "crosaVersion": 1,
    "csProcessVersion": 1,
    "id": "222f5efc2f6ea956329743c5",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "14b083f5263e79054539c45f"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_3.json
{
    "businessDay": "2024-03-14",
    "businessTimestamp": "2024-03-14T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "65c812663346d1465fe1c07e",
            "originalXnec1": {
                "assessedElementMrid": "f4efaf9dc8c100f3c841f2ca",
                "assessedElementName": "aa530da28bf0c1e5140aed44",
                "biddingZoneCode": "10YPT-REN------W",
                "conductingEquipmentMrid": "ac0b5b2f027ab2d25ef6319b",
                "contingencyMrid": "97b960e04415454e0a25c579",
                "contingencyName": "3b81234704b9c45b6230b252",
                "fAfter": 54,
                "fBefore": 60,
                "fMax": 58,
                "hasCostlyRa": false,
                "iAfter": 62,
                "iBefore": 90,
                "iMax": 35,
                "id": "28c46564b304a5f29c7c1b3f",
                "raMrid": "6629d56f622ea5b216f0d2d1",
                "tsoCode": "Transelectrica",
                "xneMrid": "f4efaf9dc8c100f3c841f2ca",
                "xneName": "aa530da28bf0c1e5140aed44"
            },
            "originalXnec2": {
                "assessedElementMrid": "3f33732b2b6891fcd205102e",
                "assessedElementName": "9b3a6bb8e53c52e1de8a8efd",
                "biddingZoneCode": "10YPL-AREA-----S",
                "conductingEquipmentMrid": "f09222d7beee2c977624e382",
                "contingencyMrid": "97b960e04415454e0a25c579",
                "contingencyName": "3b81234704b9c45b6230b252",
                "fAfter": 54,
                "fBefore": 60,
                "fMax": 58,
                "hasCostlyRa": false,
                "iAfter": 62,
                "iBefore": 90,
                "iMax": 35,
                "id": "5a30fa658e8c299ed447d650",
                "raMrid": "6629d56f622ea5b216f0d2d1",
                "tsoCode": "Transelectrica",
                "xneMrid": "3f33732b2b6891fcd205102e",
                "xneName": "9b3a6bb8e53c52e1de8a8efd"
            }
        }
    ],
    "crosaProcessType": "c269bc2a8cfe2606807fee9c",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "88c6aff58984ca2a5ec74d2d",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "d134c84f7f8cab6e2d0ee2df"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_1.json
{
    "businessDay": "2024-03-07",
    "businessTimestamp": "2024-03-07T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "7b91672ae39568ca89118142",
            "originalXnec1": {
                "assessedElementMrid": "3ee30e8c61d4d2109c288709",
                "assessedElementName": "a495a1fb0e18285caca8eec8",
                "biddingZoneCode": "38YNPSRUIMP----S",
                "conductingEquipmentMrid": "e216cf95d00371554f21b65e",
                "contingencyMrid": "fcfc077093fd4e6f1bcd7a9e",
                "contingencyName": "52b7d24348134b30efed6667",
                "fAfter": 22,
                "fBefore": 28,
                "fMax": 26,
                "hasCostlyRa": false,
                "iAfter": 96,
                "iBefore": 72,
                "iMax": 16,
                "id": "70c4a4fd91d689e8f38c9a8a",
                "raMrid": "a5ea488f27f043008f18e852",
                "tsoCode": "CEPS",
                "xneMrid": "3ee30e8c61d4d2109c288709",
                "xneName": "a495a1fb0e18285caca8eec8"
            },
            "originalXnec2": {
                "assessedElementMrid": "d89acef22f6fc2f752867f1a",
                "assessedElementName": "6c4b980ba6e7c277b34a2673",
                "biddingZoneCode": "43YLRE-------008",
                "conductingEquipmentMrid": "fa07e7a12c017ae3fea7df69",
                "contingencyMrid": "fcfc077093fd4e6f1bcd7a9e",
                "contingencyName": "52b7d24348134b30efed6667",
                "fAfter": 22,
                "fBefore": 28,
                "fMax": 26,
                "hasCostlyRa": false,
                "iAfter": 96,
                "iBefore": 72,
                "iMax": 16,
                "id": "4b62cda428f5a47c5ab47983",
                "raMrid": "a5ea488f27f043008f18e852",
                "tsoCode": "PSE",
                "xneMrid": "d89acef22f6fc2f752867f1a",
                "xneName": "6c4b980ba6e7c277b34a2673"
            }
        }
    ],
    "crosaProcessType": "9dd6594deba196f185f13bf8",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "eb8233dee1c1f390b2a7fe27",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "23c2eecaf971ecd2611572f6"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_4.json
{
    "businessDay": "2024-11-05",
    "businessTimestamp": "2024-11-05T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "5d3302f6e906479db8a8c0fd",
            "originalXnec1": {
                "assessedElementMrid": "db75fa4256529cc947a6936c",
                "assessedElementName": "b919dc98adf426f4e67fd31c",
                "biddingZoneCode": "10YSK-SEPS-----K",
                "conductingEquipmentMrid": "d3700929cad82ca4019b0915",
                "contingencyMrid": "a02f865707f52646b1182ee3",
                "contingencyName": "dfce0c9605fa66db9fed9438",
                "fAfter": 20,
                "fBefore": 26,
                "fMax": 24,
                "hasCostlyRa": false,
                "iAfter": 24,
                "iBefore": 61,
                "iMax": 15,
                "id": "11ffe2d588ae18888bbee5dd",
                "raMrid": "36616bfe4f6e246d6b39ee64",
                "tsoCode": "10XSK-SEPS-GRIDB",
                "xneMrid": "db75fa4256529cc947a6936c",
                "xneName": "b919dc98adf426f4e67fd31c"
            },
            "originalXnec2": {
                "assessedElementMrid": "9ba7fdd3cb0293b85e9fadd7",
                "assessedElementName": "223a829ec522bf9016267b98",
                "biddingZoneCode": "10YBE----------2",
                "conductingEquipmentMrid": "c053f3f6eb59dfe2b05a9d0f",
                "contingencyMrid": "a02f865707f52646b1182ee3",
                "contingencyName": "dfce0c9605fa66db9fed9438",
                "fAfter": 20,
                "fBefore": 26,
                "fMax": 24,
                "hasCostlyRa": false,
                "iAfter": 24,
                "iBefore": 61,
                "iMax": 15,
                "id": "6a9e01f88f536029ca65418a",
                "raMrid": "36616bfe4f6e246d6b39ee64",
                "tsoCode": "10X1001A1001A094",
                "xneMrid": "9ba7fdd3cb0293b85e9fadd7",
                "xneName": "223a829ec522bf9016267b98"
            }
        }
    ],
    "crosaProcessType": "67ee0129c20d234702dad123",
    "crosaVersion": 1,
    "csProcessVersion": 1,
    "id": "676339f00b89742b781649fb",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "5b2a33f2b78be6c5267a7010"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_4.json
{
    "businessDay": "2024-10-18",
    "businessTimestamp": "2024-10-18T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "817d8b6c232c7d80e9ac90ea",
            "originalXnec1": {
                "assessedElementMrid": "d79873ee3b0e563a6201e050",
                "assessedElementName": null,
                "biddingZoneCode": "df1b8ae691282040ae17380e",
                "conductingEquipmentMrid": "42ceb32b7f08d359f92500b4",
                "contingencyMrid": "df2b0e4f29b841bb401f9d7b",
                "contingencyName": null,
                "fAfter": 97.74,
                "fBefore": 29.12,
                "fMax": 61.41,
                "hasCostlyRa": false,
                "iAfter": 66.32,
                "iBefore": 69.21,
                "iMax": 95.89,
                "id": "bea84f62a1847e435a97c260",
                "raMrid": null,
                "tsoCode": "43808b3a8ab8825544ebd7e6",
                "xneMrid": "24f8e08c535f6a4cc3160973",
                "xneName": null
            },
            "originalXnec2": null
        }
    ],
    "crosaProcessType": "cc3975585c88f53d9b811e5b",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "55a4fa7945da1daee6a9f42d",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "62a3cb34f425293b3c777a4b"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_7.json
{
    "businessDay": "2024-08-12",
    "businessTimestamp": "2024-08-12T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "534678022d2845125b700e2d",
            "originalXnec1": {
                "assessedElementMrid": "c980ed71e5da942c61ebed63",
                "assessedElementName": "e0207ec03ac09b7c4c081536",
                "biddingZoneCode": "10YCB-NL-------V",
                "conductingEquipmentMrid": "53ed856fd73ce23b1afc792c",
                "contingencyMrid": "b6ae998d4152a712a41f913d",
                "contingencyName": "ed85949c9e48a5c43d3aab56",
                "fAfter": 66,
                "fBefore": 72,
                "fMax": 70,
                "hasCostlyRa": false,
                "iAfter": 94,
                "iBefore": 91,
                "iMax": 94,
                "id": "e02bd9798463b4fda03be307",
                "raMrid": "e9cb18a49a577d7525b3caf8",
                "tsoCode": "10X1001A1001A361",
                "xneMrid": "c980ed71e5da942c61ebed63",
                "xneName": "e0207ec03ac09b7c4c081536"
            },
            "originalXnec2": {
                "assessedElementMrid": "8f85c923c5e63293b4534c7c",
                "assessedElementName": "a2940e580c10032b9bbabe39",
                "biddingZoneCode": "10YCB-CZECH-REP5",
                "conductingEquipmentMrid": "32f2015edcfc46aa6ec834e9",
                "contingencyMrid": "b6ae998d4152a712a41f913d",
                "contingencyName": "ed85949c9e48a5c43d3aab56",
                "fAfter": 66,
                "fBefore": 72,
                "fMax": 70,
                "hasCostlyRa": false,
                "iAfter": 94,
                "iBefore": 91,
                "iMax": 94,
                "id": "e04806721dc79c9101741f02",
                "raMrid": "e9cb18a49a577d7525b3caf8",
                "tsoCode": "10XCZ-CEPS-GRIDE",
                "xneMrid": "8f85c923c5e63293b4534c7c",
                "xneName": "a2940e580c10032b9bbabe39"
            }
        }
    ],
    "crosaProcessType": "cd8bc47c7deae720104205c6",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "181250f5e17bd6c96c48f953",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "42fa1df6b5e909925b2c9479"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_2.json
{
    "businessDay": "2024-08-26",
    "businessTimestamp": "2024-08-26T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "6ea34ce2ba7dd07916df18de",
            "originalXnec1": {
                "assessedElementMrid": "9a7dfaa2eb9c02b8a83e30a9",
                "assessedElementName": "48d4c049ed27acb837ffa378",
                "biddingZoneCode": "10YCB-BE-------T",
                "conductingEquipmentMrid": "05b8eb3514d9e5349cbc158f",
                "contingencyMrid": "ce7c826ef303304aa6fb61cf",
                "contingencyName": "765baf3acd88aa7e6f405dc5",
                "fAfter": 1,
                "fBefore": 7,
                "fMax": 5,
                "hasCostlyRa": true,
                "iAfter": 77,
                "iBefore": 50,
                "iMax": 26,
                "id": "aa7ad5f1167084744d86cbbb",
                "raMrid": "a70ecedd8d2f2dde0dd9eac6",
                "tsoCode": "10X1001A1001A094",
                "xneMrid": "9a7dfaa2eb9c02b8a83e30a9",
                "xneName": "48d4c049ed27acb837ffa378"
            },
            "originalXnec2": {
                "assessedElementMrid": "bffdaf4e5320a2ffb1a21eb0",
                "assessedElementName": "0d924420a8e8870500fa329a",
                "biddingZoneCode": "10Y1001C--00002H",
                "conductingEquipmentMrid": "3a6deba652702ec1b6ce0d3e",
                "contingencyMrid": "ce7c826ef303304aa6fb61cf",
                "contingencyName": "765baf3acd88aa7e6f405dc5",
                "fAfter": 1,
                "fBefore": 7,
                "fMax": 5,
                "hasCostlyRa": true,
                "iAfter": 77,
                "iBefore": 50,
                "iMax": 26,
                "id": "49e2d944ea6f19877214c370",
                "raMrid": "a70ecedd8d2f2dde0dd9eac6",
                "tsoCode": "10XDE-RWENET---W",
                "xneMrid": "bffdaf4e5320a2ffb1a21eb0",
                "xneName": "0d924420a8e8870500fa329a"
            }
        }
    ],
    "crosaProcessType": "07b8cce5df82de01890c813f",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "737ad8d7259ed976de030231",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "562e9a829c76f04cf56845af"
}
