=== arielmbomakaeyros/como-files/SelectedXnecResult_Scheme_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/SelectedXnecResult_Scheme",
    "title": "selectedXnecResult",
    "type": "object",
    "description": "XNEC selection result - selected XNECs",
    "properties": {
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "convertedXnecList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/convertedXnec"
            }
        },
        "crosaProcessType": {
            "type": "string"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "id": {
            "description": "Unique identifier of the selected result set",
            "type": "string"
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "xnecSelectionInputId": {
            "description": "Reference to unique identifier of the related XNEC selection input data set",
            "type": "string"
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_SELECTED_XNEC_RESULT"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "convertedXnec": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier of the converted XNEC (a combination of original XNEC(s) for the related contingency)",
                    "type": "string"
                },
                "originalXnec1": {
                    "description": "First original XNEC's data",
                    "$ref": "#/definitions/originalXnecData"
                },
                "originalXnec2": {
                    "description": "Second original XNEC's data",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/originalXnecData"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "id",
                "originalXnec1"
            ]
        },
        "originalXnecData": {
            "type": "object",
            "properties": {
                "assessedElementMrid": {
                    "description": "Mrid of the assessed element from assessed element (flat) list.",
                    "type": "string"
                },
                "assessedElementName": {
                    "description": "Name of the assessed element from the assessed element flat list.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "biddingZoneCode": {
                    "description": "EIC code of the bidding zone",
                    "type": "string"
                },
                "conductingEquipmentMrid": {
                    "description": "Mrid of the conducting equipment from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "contingencyMrid": {
                    "description": "Mrid of the related contingency",
                    "type": "string"
                },
                "contingencyName": {
                    "description": "Name of the contingency",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "fAfter": {
                    "type": "number"
                },
                "fBefore": {
                    "description": "Current on XNEC before RAO [A]",
                    "type": "number"
                },
                "fMax": {
                    "type": "number"
                },
                "hasCostlyRa": {
                    "description": "Indication whether the related costly remedial action was materialized for the XNEC (true) or not (false)",
                    "type": "boolean"
                },
                "iAfter": {
                    "description": "Current on XNEC after RAC, including agreed XRAs impact [A]",
                    "type": "number"
                },
                "iBefore": {
                    "type": "number"
                },
                "iMax": {
                    "description": "Maximum current on XNEC [A]",
                    "type": "number"
                },
                "id": {
                    "description": "Unique identifier of the original XNEC",
                    "type": "string"
                },
                "raMrid": {
                    "description": "Mrid of the related costly RA",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "tsoCode": {
                    "description": "EIC of the related TSO",
                    "type": "string"
                },
                "xneMrid": {
                    "description": "Mrid of the XNE from the CGM",
                    "type": "string"
                },
                "xneName": {
                    "description": "Name of the XNE from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "assessedElementMrid",
                "biddingZoneCode",
                "contingencyMrid",
                "fAfter",
                "fBefore",
                "fMax",
                "hasCostlyRa",
                "iAfter",
                "iBefore",
                "iMax",
                "id",
                "tsoCode",
                "xneMrid"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaProcessType",
        "crosaVersion",
        "csProcessVersion",
        "id",
        "timeHorizon",
        "xnecSelectionInputId"
    ]
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_6.json
{
    "businessDay": "2024-10-08",
    "businessTimestamp": "2024-10-08T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "7a6dcb4124cb21817c419033",
            "originalXnec1": {
                "assessedElementMrid": "666f29617be6fb4ddbe82068",
                "assessedElementName": "c9c334c33c592256ec309894",
                "biddingZoneCode": " 10Y1001C--00010I",
                "conductingEquipmentMrid": "0b48682d5592262d6ee4eaa4",
                "contingencyMrid": "66fca53e328a74d5b76313e0",
                "contingencyName": "fe359b666259db79a00ee3ba",
                "fAfter": 54,
                "fBefore": 60,
                "fMax": 58,
                "hasCostlyRa": true,
                "iAfter": 61,
                "iBefore": 41,
                "iMax": 61,
                "id": "53d8777f9caf87aaca738de9",
                "raMrid": "185e95a958d6337c29279f93",
                "tsoCode": "10XDE-VE-TRANSMK",
                "xneMrid": "666f29617be6fb4ddbe82068",
                "xneName": "c9c334c33c592256ec309894"
            },
            "originalXnec2": {
                "assessedElementMrid": "fbaf9bc2b8c6a995d4ac498e",
                "assessedElementName": "f9e3ce5a0c2c40f6e8955697",
                "biddingZoneCode": "10YCB-CZECH-REP5",
                "conductingEquipmentMrid": "cdcaae9c242c9b59f66456d1",
                "contingencyMrid": "66fca53e328a74d5b76313e0",
                "contingencyName": "fe359b666259db79a00ee3ba",
                "fAfter": 54,
                "fBefore": 60,
                "fMax": 58,
                "hasCostlyRa": true,
                "iAfter": 61,
                "iBefore": 41,
                "iMax": 61,
                "id": "742cd1e22a77d26d4a3557c6",
                "raMrid": "185e95a958d6337c29279f93",
                "tsoCode": "10XCZ-CEPS-GRIDE",
                "xneMrid": "fbaf9bc2b8c6a995d4ac498e",
                "xneName": "f9e3ce5a0c2c40f6e8955697"
            }
        }
    ],
    "crosaProcessType": "e14dbdd837aff4e791acd5bc",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "f7072a9acd09dbf233aef4ed",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "a5715201eb986d0a804055d0"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_6.json
{
    "businessDay": "2025-01-03",
    "businessTimestamp": "2025-01-03T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "c3560386b3930ed8b5012c3b",
            "originalXnec1": {
                "assessedElementMrid": "aa3766f95a60c56077c94f81",
                "assessedElementName": null,
                "biddingZoneCode": "bb9e1e095cab7a8bb6e7730c",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "c781de5fe01373683f3f138d",
                "contingencyName": "99590254e5d7c9753d3547e2",
                "fAfter": 96.1,
                "fBefore": 98.32,
                "fMax": 89.82,
                "hasCostlyRa": true,
                "iAfter": 45.41,
                "iBefore": 12.84,
                "iMax": 51.4,
                "id": "3c7fd5aca5924e1dbec1f19d",
                "raMrid": "b9240eff2592e4a42ec39523",
                "tsoCode": "7af6a8c4184ce072552cd659",
                "xneMrid": "88f9616d44b37e0808ec05f3",
                "xneName": "054dff5d0c7dd50587b00e21"
            },
            "originalXnec2": {
                "assessedElementMrid": "0a65a3a2e5b872ac5fbb1f47",
                "assessedElementName": "bdc478f51f1c275f94adbc2d",
                "biddingZoneCode": "d37217e4e719f08c46f47af9",
                "conductingEquipmentMrid": "f7243183865cc469feb17dce",
                "contingencyMrid": "bb40c5c64795c1a08729e74d",
                "contingencyName": null,
                "fAfter": 26.72,
                "fBefore": 63.67,
                "fMax": 83.92,
                "hasCostlyRa": false,
                "iAfter": 70.9,
                "iBefore": 80.68,
                "iMax": 93.17,
                "id": "68c17a6c000da23e0bf6f047",
                "raMrid": null,
                "tsoCode": "e56de346264d06b14537f044",
                "xneMrid": "4248a5c0df1b921593d6d48d",
                "xneName": null
            }
        }
    ],
    "crosaProcessType": "0a3d18a1f82cf8e411f16de6",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "86291cec227c854cdba4a00d",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "2a84c762eba2be5f7c61f789"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_9.json
{
    "businessDay": "2024-10-23",
    "businessTimestamp": "2024-10-23T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "9caeb171ea79e1f6524a574f",
            "originalXnec1": {
                "assessedElementMrid": "6f87fc62560eaae155c23b6e",
                "assessedElementName": "cca06372b5378a26168ed874",
                "biddingZoneCode": "10YBE----------2",
                "conductingEquipmentMrid": "d643d161b16e4d0dead49f27",
                "contingencyMrid": "311d40dea40927adea9c2950",
                "contingencyName": "f585691efa47a518b8b30955",
                "fAfter": 37,
                "fBefore": 43,
                "fMax": 41,
                "hasCostlyRa": true,
                "iAfter": 35,
                "iBefore": 40,
                "iMax": 66,
                "id": "b6dd4b9b99dfce7bbc6c9dff",
                "raMrid": "52ebe739e082aa2ef0e6af1b",
                "tsoCode": "10X1001A1001A094",
                "xneMrid": "6f87fc62560eaae155c23b6e",
                "xneName": "cca06372b5378a26168ed874"
            },
            "originalXnec2": {
                "assessedElementMrid": "957d23598515f02e81ebea6e",
                "assessedElementName": "96913838b1b988ae547a2d35",
                "biddingZoneCode": "10YAT-APG------L",
                "conductingEquipmentMrid": "c949908e2b95b19fc1e2eae8",
                "contingencyMrid": "311d40dea40927adea9c2950",
                "contingencyName": "f585691efa47a518b8b30955",
                "fAfter": 37,
                "fBefore": 43,
                "fMax": 41,
                "hasCostlyRa": true,
                "iAfter": 35,
                "iBefore": 40,
                "iMax": 66,
                "id": "c37afb579cd8acc748b4e0ed",
                "raMrid": "52ebe739e082aa2ef0e6af1b",
                "tsoCode": "10XAT-APG------Z",
                "xneMrid": "957d23598515f02e81ebea6e",
                "xneName": "96913838b1b988ae547a2d35"
            }
        }
    ],
    "crosaProcessType": "68da633afef84ff0432e4aab",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "1f64432bfb7dbe03f21d120d",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "1e1ef18159058c256e3cce27"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_7.json
{
    "businessDay": "2024-05-15",
    "businessTimestamp": "2024-05-15T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "91e49e879841eebda2f485ed",
            "originalXnec1": {
                "assessedElementMrid": "3e1c7e65fa5199c94c5aa230",
                "assessedElementName": null,
                "biddingZoneCode": "ddfc8991b4781569dfc20376",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "eb26f55018cf5fdb24dc8ea4",
                "contingencyName": null,
                "fAfter": 34.87,
                "fBefore": 33.98,
                "fMax": 74.68,
                "hasCostlyRa": true,
                "iAfter": 49.61,
                "iBefore": 57.69,
                "iMax": 20.85,
                "id": "1f9d038b79056b0db1c38e38",
                "raMrid": null,
                "tsoCode": "f6cc95b6bcf7c0ee6fd84887",
                "xneMrid": "24e3a0d744cf0504738f9dec",
                "xneName": "c0ac64ce57c838f6263b835d"
            },
            "originalXnec2": {
                "assessedElementMrid": "925abcb4eb1d6978dee05427",
                "assessedElementName": null,
                "biddingZoneCode": "c4da388ce4e300c325118dbc",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "4f18e3ef7353025f081dfc0b",
                "contingencyName": "3598af9187da98e301af5402",
                "fAfter": 53.98,
                "fBefore": 26.97,
                "fMax": 72.72,
                "hasCostlyRa": false,
                "iAfter": 46.99,
                "iBefore": 36.26,
                "iMax": 73.01,
                "id": "92bcd8da4aadd702d90e400b",
                "raMrid": "260236ed3117aa72ce1482eb",
                "tsoCode": "4bfc08a7b0f194f778cac2d5",
                "xneMrid": "ca96ab3f510a86eefb554113",
                "xneName": null
            }
        }
    ],
    "crosaProcessType": "6c73d83e09db98ff170e30ff",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "2ac45ead9941d8d94433912f",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "91dfd4228eaf8c8fdddb146a"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_5.json
{
    "businessDay": "2024-12-31",
    "businessTimestamp": "2024-12-31T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "e9abc7664e14e59fe427add9",
            "originalXnec1": {
                "assessedElementMrid": "78f69010c640159607b80546",
                "assessedElementName": "eb5e62755c54e3a4d4ed3b43",
                "biddingZoneCode": "10YAT-APG------L",
                "conductingEquipmentMrid": "2238b15a2f294a20e7a84887",
                "contingencyMrid": "c374aa4d2a0d3b58393313fe",
                "contingencyName": "6c3a7f5d8098d26bbd5ff791",
                "fAfter": 66,
                "fBefore": 72,
                "fMax": 70,
                "hasCostlyRa": true,
                "iAfter": 96,
                "iBefore": 59,
                "iMax": 17,
                "id": "f74f183557733ffaa035aa4c",
                "raMrid": "6aef5f010ec8c84f11388f07",
                "tsoCode": "10XAT-APG------Z",
                "xneMrid": "78f69010c640159607b80546",
                "xneName": "eb5e62755c54e3a4d4ed3b43"
            },
            "originalXnec2": {
                "assessedElementMrid": "6ee4bc92087bf1cc0e537ad0",
                "assessedElementName": "82f1f67a9512542be4f9281b",
                "biddingZoneCode": "10YBE----------2",
                "conductingEquipmentMrid": "4786eddc8a9e7203bcdf4bd3",
                "contingencyMrid": "c374aa4d2a0d3b58393313fe",
                "contingencyName": "6c3a7f5d8098d26bbd5ff791",
                "fAfter": 66,
                "fBefore": 72,
                "fMax": 70,
                "hasCostlyRa": true,
                "iAfter": 96,
                "iBefore": 59,
                "iMax": 17,
                "id": "18ea834e14ea7f9c7850ca0a",
                "raMrid": "6aef5f010ec8c84f11388f07",
                "tsoCode": "10X1001A1001A094",
                "xneMrid": "6ee4bc92087bf1cc0e537ad0",
                "xneName": "82f1f67a9512542be4f9281b"
            }
        }
    ],
    "crosaProcessType": "d03f7625bfd4bfac3796bcee",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "5b9098582f795117cab13d1b",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "e85eb44bdf2f4d4405bcaa1f"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_7.json
{
    "businessDay": "2024-05-22",
    "businessTimestamp": "2024-05-22T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "46b56d2c8ee22fa2ada781fb",
            "originalXnec1": {
                "assessedElementMrid": "7e09a5276cdc2e43e537c626",
                "assessedElementName": "a07068eab7f053d9d1a74788",
                "biddingZoneCode": "10YPL-AREA-----S",
                "conductingEquipmentMrid": "463951803619821ad4d1c210",
                "contingencyMrid": "dd63844e3726d40f73d9db1b",
                "contingencyName": "7eaab86e9fc299799d31dbbd",
                "fAfter": 10,
                "fBefore": 16,
                "fMax": 14,
                "hasCostlyRa": false,
                "iAfter": 26,
                "iBefore": 11,
                "iMax": 85,
                "id": "37df7897ed6be2d4c97f8d23",
                "raMrid": "86baf53ffed2d56f9554a13a",
                "tsoCode": "10XPL-TSO------P",
                "xneMrid": "7e09a5276cdc2e43e537c626",
                "xneName": "a07068eab7f053d9d1a74788"
            },
            "originalXnec2": {
                "assessedElementMrid": "efb61b86ce5db35695098796",
                "assessedElementName": "fba7af98b267a3bcde5ac1b4",
                "biddingZoneCode": "10YHU-MAVIR----U",
                "conductingEquipmentMrid": "299c7d33f347a82118cdc335",
                "contingencyMrid": "dd63844e3726d40f73d9db1b",
                "contingencyName": "7eaab86e9fc299799d31dbbd",
                "fAfter": 10,
                "fBefore": 16,
                "fMax": 14,
                "hasCostlyRa": false,
                "iAfter": 26,
                "iBefore": 11,
                "iMax": 85,
                "id": "93bae37172c9522430e787a6",
                "raMrid": "86baf53ffed2d56f9554a13a",
                "tsoCode": "10X1001A1001A329",
                "xneMrid": "efb61b86ce5db35695098796",
                "xneName": "fba7af98b267a3bcde5ac1b4"
            }
        }
    ],
    "crosaProcessType": "f8f1b95a935ac46fcb78275b",
    "crosaVersion": 1,
    "csProcessVersion": 1,
    "id": "8f9fa4812af0bd0fa118b935",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "90c6a303e7dc35fc3b9b9d18"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_1.json
{
    "businessDay": "2024-08-22",
    "businessTimestamp": "2024-08-22T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "c8b8706d57b03afe292a2ed1",
            "originalXnec1": {
                "assessedElementMrid": "271d11837bf6d883db6d7dff",
                "assessedElementName": null,
                "biddingZoneCode": "4742b8d56bb611955c62f47f",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "f6a83dd4a2e1d522a57beeb4",
                "contingencyName": null,
                "fAfter": 55.72,
                "fBefore": 63.69,
                "fMax": 23.93,
                "hasCostlyRa": false,
                "iAfter": 29.78,
                "iBefore": 69.38,
                "iMax": 88.56,
                "id": "921f53b2599e3e3c9eb2693e",
                "raMrid": "3bd8ac1df8715cc7caffce50",
                "tsoCode": "cd845f7cd2fcd4fc239509c0",
                "xneMrid": "815957b844e11f627f42ab30",
                "xneName": "d6a7124aeb7caf898406cff8"
            },
            "originalXnec2": {
                "assessedElementMrid": "0735ebbf1bf8a9d8e836fd9e",
                "assessedElementName": "51b36c335488bc8fad5c61ff",
                "biddingZoneCode": "468be0902ee60ce37e3a56de",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "845765838df430f13c8cc5f7",
                "contingencyName": null,
                "fAfter": 70.29,
                "fBefore": 44.23,
                "fMax": 34.78,
                "hasCostlyRa": true,
                "iAfter": 92.14,
                "iBefore": 23.98,
                "iMax": 26.49,
                "id": "940788a7e7473b84c1b7ffac",
                "raMrid": "4773e26cf88e7708b6106070",
                "tsoCode": "e900d59df6b5fb7dba178185",
                "xneMrid": "8116f376ab4b4158803bdeae",
                "xneName": null
            }
        }
    ],
    "crosaProcessType": "dea229cc15239cd8457c99f2",
    "crosaVersion": 1,
    "csProcessVersion": 3,
    "id": "f39c54aaf6671499e6e1c02b",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "6f2e4f95c8107c27d9867f8a"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_5.json
{
    "businessDay": "2024-04-26",
    "businessTimestamp": "2024-04-26T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "42d2d9761d2d7f22bd0c475e",
            "originalXnec1": {
                "assessedElementMrid": "997da88362e18d44b32ddf85",
                "assessedElementName": null,
                "biddingZoneCode": "347a21e3b883402225f19776",
                "conductingEquipmentMrid": "4b2b97abe1474fafd626a55d",
                "contingencyMrid": "6ff10d44f875a38f447ea65f",
                "contingencyName": null,
                "fAfter": 25.2,
                "fBefore": 10.44,
                "fMax": 73.33,
                "hasCostlyRa": true,
                "iAfter": 60.74,
                "iBefore": 69.42,
                "iMax": 1.27,
                "id": "c119f84956a8600e323a9fbc",
                "raMrid": "454f3a333dc892dad414d346",
                "tsoCode": "3038cfdbcf0c4929f9275398",
                "xneMrid": "614fcc72e39f6cfb60da5cc5",
                "xneName": null
            },
            "originalXnec2": {
                "assessedElementMrid": "1fa324ac0602f38a1ddd04df",
                "assessedElementName": "5b24389e23acbfc232b58249",
                "biddingZoneCode": "bd80d3c900fe8426ffa658f8",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "0f5ccf21ec629b10e48792e4",
                "contingencyName": null,
                "fAfter": 54.51,
                "fBefore": 90.07,
                "fMax": 27.03,
                "hasCostlyRa": true,
                "iAfter": 37.7,
                "iBefore": 80.82,
                "iMax": 40.99,
                "id": "2544fab195d115b60f02bbf4",
                "raMrid": null,
                "tsoCode": "5b5bd151d6fac3f6cc5f4ed9",
                "xneMrid": "b16b92f8d4123e3b9a327f19",
                "xneName": "4356e72ad5d74ff612f48a36"
            }
        }
    ],
    "crosaProcessType": "f3c218754a7f57ac70d94702",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "4922cb46993eb87ebdc9f3d3",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "8e9c0ec61be222a9bfaffa26"
}
