=== arielmbomakaeyros/como-files/SelectedXnecResult_Scheme_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/SelectedXnecResult_Scheme",
    "title": "selectedXnecResult",
    "type": "object",
    "description": "XNEC selection result - selected XNECs",
    "properties": {
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "convertedXnecList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/convertedXnec"
            }
        },
        "crosaProcessType": {
            "type": "string"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "id": {
            "description": "Unique identifier of the selected result set",
            "type": "string"
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "xnecSelectionInputId": {
            "description": "Reference to unique identifier of the related XNEC selection input data set",
            "type": "string"
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_SELECTED_XNEC_RESULT"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "convertedXnec": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier of the converted XNEC (a combination of original XNEC(s) for the related contingency)",
                    "type": "string"
                },
                "originalXnec1": {
                    "description": "First original XNEC's data",
                    "$ref": "#/definitions/originalXnecData"
                },
                "originalXnec2": {
                    "description": "Second original XNEC's data",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/originalXnecData"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "id",
                "originalXnec1"
            ]
        },
        "originalXnecData": {
            "type": "object",
            "properties": {
                "assessedElementMrid": {
                    "description": "Mrid of the assessed element from assessed element (flat) list.",
                    "type": "string"
                },
                "assessedElementName": {
                    "description": "Name of the assessed element from the assessed element flat list.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "biddingZoneCode": {
                    "description": "EIC code of the bidding zone",
                    "type": "string"
                },
                "conductingEquipmentMrid": {
                    "description": "Mrid of the conducting equipment from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "contingencyMrid": {
                    "description": "Mrid of the related contingency",
                    "type": "string"
                },
                "contingencyName": {
                    "description": "Name of the contingency",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "fAfter": {
                    "type": "number"
                },
                "fBefore": {
                    "description": "Current on XNEC before RAO [A]",
                    "type": "number"
                },
                "fMax": {
                    "type": "number"
                },
                "hasCostlyRa": {
                    "description": "Indication whether the related costly remedial action was materialized for the XNEC (true) or not (false)",
                    "type": "boolean"
                },
                "iAfter": {
                    "description": "Current on XNEC after RAC, including agreed XRAs impact [A]",
                    "type": "number"
                },
                "iBefore": {
                    "type": "number"
                },
                "iMax": {
                    "description": "Maximum current on XNEC [A]",
                    "type": "number"
                },
                "id": {
                    "description": "Unique identifier of the original XNEC",
                    "type": "string"
                },
                "raMrid": {
                    "description": "Mrid of the related costly RA",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "tsoCode": {
                    "description": "EIC of the related TSO",
                    "type": "string"
                },
                "xneMrid": {
                    "description": "Mrid of the XNE from the CGM",
                    "type": "string"
                },
                "xneName": {
                    "description": "Name of the XNE from the CGM",
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "assessedElementMrid",
                "biddingZoneCode",
                "contingencyMrid",
                "fAfter",
                "fBefore",
                "fMax",
                "hasCostlyRa",
                "iAfter",
                "iBefore",
                "iMax",
                "id",
                "tsoCode",
                "xneMrid"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaProcessType",
        "crosaVersion",
        "csProcessVersion",
        "id",
        "timeHorizon",
        "xnecSelectionInputId"
    ]
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_2.json
{
    "businessDay": "2024-05-09",
    "businessTimestamp": "2024-05-09T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "4940220f67a890b789cb3371",
            "originalXnec1": {
                "assessedElementMrid": "60a2b285d1f49dac35dd1e4d",
                "assessedElementName": null,
                "biddingZoneCode": "9e4a6d6679ebbe6a480ededf",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "2a02d01855bf857e5c23a94c",
                "contingencyName": "55b836ac8b32afa57cc207d9",
                "fAfter": 75.27,
                "fBefore": 2.48,
                "fMax": 32.22,
                "hasCostlyRa": false,
                "iAfter": 71.09,
                "iBefore": 31.65,
                "iMax": 12.27,
                "id": "eadf0f9c114078a331d42595",
                "raMrid": null,
                "tsoCode": "6017af1ae485bd55d9d627b4",
                "xneMrid": "45425f431a7f593841194af1",
                "xneName": null
            },
            "originalXnec2": {
                "assessedElementMrid": "b2eb23fd38a91e9f79b09cc7",
                "assessedElementName": "76a7c2d461cd10a946641329",
                "biddingZoneCode": "89e7b70c52f121ca3eddaed0",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "e8bffb777fb5eec0f1b516bb",
                "contingencyName": "155c3a434de8816164f40b95",
                "fAfter": 63.96,
                "fBefore": 52.38,
                "fMax": 79.76,
                "hasCostlyRa": false,
                "iAfter": 27.78,
                "iBefore": 83.56,
                "iMax": 19.69,
                "id": "dc10c743839cb2d040428e18",
                "raMrid": null,
                "tsoCode": "be8ae0e186d2a9101fd167c7",
                "xneMrid": "8f1caa4a91ef90d741d1e45a",
                "xneName": "88b2e5379050824489ba4e96"
            }
        }
    ],
    "crosaProcessType": "55614a65404598ad1eada3c2",
    "crosaVersion": 1,
    "csProcessVersion": 3,
    "id": "1f0a8e69a492ce0eb8909968",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "04bea84f60a8610869562a89"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_8.json
{
    "businessDay": "2024-07-29",
    "businessTimestamp": "2024-07-29T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "9e159e976757f0364f3a91a4",
            "originalXnec1": {
                "assessedElementMrid": "b1e80c097cd4277aeb6117ed",
                "assessedElementName": "c6a1142c278b5cc0a8773d52",
                "biddingZoneCode": "10YSI-ELES-----O",
                "conductingEquipmentMrid": "2f22cd2979952796a63685bd",
                "contingencyMrid": "26c9f4bdf1f80b7b79012e51",
                "contingencyName": "bd67c0510bf18f0040d4c80d",
                "fAfter": 44,
                "fBefore": 50,
                "fMax": 48,
                "hasCostlyRa": false,
                "iAfter": 55,
                "iBefore": 100,
                "iMax": 71,
                "id": "d0ab1077799b93685fe14a30",
                "raMrid": "48730cd76fff4dec59e467b1",
                "tsoCode": "10XSI-ELES-----1",
                "xneMrid": "b1e80c097cd4277aeb6117ed",
                "xneName": "c6a1142c278b5cc0a8773d52"
            },
            "originalXnec2": {
                "assessedElementMrid": "74b28fc0d4d380c7fef4e2e7",
                "assessedElementName": "5460d27190e510f720cffbb6",
                "biddingZoneCode": "10YFR-RTE------C",
                "conductingEquipmentMrid": "17eb59b51df010a311fb9fa8",
                "contingencyMrid": "26c9f4bdf1f80b7b79012e51",
                "contingencyName": "bd67c0510bf18f0040d4c80d",
                "fAfter": 44,
                "fBefore": 50,
                "fMax": 48,
                "hasCostlyRa": false,
                "iAfter": 55,
                "iBefore": 100,
                "iMax": 71,
                "id": "d3da427e13d6d45d72c7872c",
                "raMrid": "48730cd76fff4dec59e467b1",
                "tsoCode": "10XFR-RTE------Q",
                "xneMrid": "74b28fc0d4d380c7fef4e2e7",
                "xneName": "5460d27190e510f720cffbb6"
            }
        }
    ],
    "crosaProcessType": "0dbcc3b3a50533e728f6b6dc",
    "crosaVersion": 1,
    "csProcessVersion": 3,
    "id": "22f7ab8cb14bba7ee1a666bb",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "860348f5522a088157fcff4e"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult/SelectedXnecResult__file_5.json
{
    "businessDay": "2024-05-29",
    "businessTimestamp": "2024-05-29T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "cb1da73af6c7c1a2765667c9",
            "originalXnec1": {
                "assessedElementMrid": "f56c3cae735eba9b3f406760",
                "assessedElementName": "508e96da6ee7d3a31667bd2d",
                "biddingZoneCode": "10Y1001A1001A80L",
                "conductingEquipmentMrid": "208cf31ea374ca4f9a7125ce",
                "contingencyMrid": "4177c4df85ff826d134a1196",
                "contingencyName": "fead90836544f610ff8a8ba6",
                "fAfter": 21,
                "fBefore": 27,
                "fMax": 25,
                "hasCostlyRa": true,
                "iAfter": 43,
                "iBefore": 36,
                "iMax": 55,
                "id": "cc6400ab866702eab2aa53ce",
                "raMrid": "66b820df3a5f220d3eed32bb",
                "tsoCode": "MAVIR",
                "xneMrid": "f56c3cae735eba9b3f406760",
                "xneName": "508e96da6ee7d3a31667bd2d"
            },
            "originalXnec2": {
                "assessedElementMrid": "1761db6a9f8f692dc3e14b86",
                "assessedElementName": "87912dfb511cab771eba1b2f",
                "biddingZoneCode": "10YDK-2--------M",
                "conductingEquipmentMrid": "d23b9d43ed26ec8d56417e3c",
                "contingencyMrid": "4177c4df85ff826d134a1196",
                "contingencyName": "fead90836544f610ff8a8ba6",
                "fAfter": 21,
                "fBefore": 27,
                "fMax": 25,
                "hasCostlyRa": true,
                "iAfter": 43,
                "iBefore": 36,
                "iMax": 55,
                "id": "dae4c993117c504a57e926dc",
                "raMrid": "66b820df3a5f220d3eed32bb",
                "tsoCode": "APG",
                "xneMrid": "1761db6a9f8f692dc3e14b86",
                "xneName": "87912dfb511cab771eba1b2f"
            }
        }
    ],
    "crosaProcessType": "32f28d5b0f1043b35fa0bf42",
    "crosaVersion": 1,
    "csProcessVersion": 4,
    "id": "e5d763b7740da9ec084af1c2",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "74582cf53c6f10e2a86ccbbb"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_8.json
{
    "businessDay": "2024-08-28",
    "businessTimestamp": "2024-08-28T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "7b4624f89d24faaea6f67554",
            "originalXnec1": {
                "assessedElementMrid": "7ffc105293aa939714544eb1",
                "assessedElementName": null,
                "biddingZoneCode": "e0a263f5ca1360086af01908",
                "conductingEquipmentMrid": "dba28cf442b073664c1fc103",
                "contingencyMrid": "ec81a1929d5a5eaf557247ae",
                "contingencyName": null,
                "fAfter": 23.85,
                "fBefore": 85.62,
                "fMax": 66.02,
                "hasCostlyRa": true,
                "iAfter": 63.42,
                "iBefore": 32.31,
                "iMax": 99.76,
                "id": "e0459622c970625a47f6fa1f",
                "raMrid": "9ab94ae403b8b72d3763223e",
                "tsoCode": "c5132b31a0bcd2f8c6d6a7a7",
                "xneMrid": "2b0826fcd3126715c9b3819e",
                "xneName": null
            },
            "originalXnec2": null
        }
    ],
    "crosaProcessType": "b92ff68fe0b0c8a58a5ba8a7",
    "crosaVersion": 1,
    "csProcessVersion": 1,
    "id": "d0ae22865765dd6b61236fc7",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "764f9343d0dadadb8820940b"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_2.json
{
    "businessDay": "2024-12-18",
    "businessTimestamp": "2024-12-18T02:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "44819508b869ef10eee3fc9e",
            "originalXnec1": {
                "assessedElementMrid": "148b9d4ded3a6fb5500ea864",
                "assessedElementName": "cc8a8cd08ee70956f7556ef5",
                "biddingZoneCode": "10YHU-MAVIR----U",
                "conductingEquipmentMrid": "f3abca368d2281f74fbf9055",
                "contingencyMrid": "3755a60e070c1116d4bc16fa",
                "contingencyName": "764bb0ff78c95616cfcb0359",
                "fAfter": 27,
                "fBefore": 33,
                "fMax": 31,
                "hasCostlyRa": true,
                "iAfter": 90,
                "iBefore": 45,
                "iMax": 34,
                "id": "59c44ecb39372de77873efde",
                "raMrid": "76e5008ab9706bb07a8d3e1d",
                "tsoCode": "10X1001A1001A329",
                "xneMrid": "148b9d4ded3a6fb5500ea864",
                "xneName": "cc8a8cd08ee70956f7556ef5"
            },
            "originalXnec2": {
                "assessedElementMrid": "754eeea2c74021fe3b7275d6",
                "assessedElementName": "158761d2cd123e4e6e1c2d3d",
                "biddingZoneCode": "10Y1001A1001A82H",
                "conductingEquipmentMrid": "ba5c279f0d2dd4f589ba5ac7",
                "contingencyMrid": "3755a60e070c1116d4bc16fa",
                "contingencyName": "764bb0ff78c95616cfcb0359",
                "fAfter": 27,
                "fBefore": 33,
                "fMax": 31,
                "hasCostlyRa": true,
                "iAfter": 90,
                "iBefore": 45,
                "iMax": 34,
                "id": "a4ede6fa8d4d0a1c9c776fbe",
                "raMrid": "76e5008ab9706bb07a8d3e1d",
                "tsoCode": "10XDE-EON-NETZ-C",
                "xneMrid": "754eeea2c74021fe3b7275d6",
                "xneName": "158761d2cd123e4e6e1c2d3d"
            }
        }
    ],
    "crosaProcessType": "85541ff7cf3fa91355ea6b34",
    "crosaVersion": 1,
    "csProcessVersion": 3,
    "id": "9dc80003c3e88becd03a282e",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "7a059227dd3b0c2bd9d0b606"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_1.json
{
    "businessDay": "2024-10-31",
    "businessTimestamp": "2024-10-31T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "cd63bdc454b437359f7457e8",
            "originalXnec1": {
                "assessedElementMrid": "95175e25ad5547e81bb8e48e",
                "assessedElementName": "e85fe78f8dd5af86202cf381",
                "biddingZoneCode": "10Y1001A1001A82H",
                "conductingEquipmentMrid": "68b034f1e5056149f8bd6cf4",
                "contingencyMrid": "e44fb2182adc95bbe632aaa2",
                "contingencyName": "9e626c2c8319f1c75f5caeb2",
                "fAfter": 58,
                "fBefore": 64,
                "fMax": 62,
                "hasCostlyRa": true,
                "iAfter": 25,
                "iBefore": 34,
                "iMax": 87,
                "id": "5bd760c773234659efaacd4c",
                "raMrid": "a23a7d743e3ebd4d0149ce95",
                "tsoCode": "10XDE-RWENET---W",
                "xneMrid": "95175e25ad5547e81bb8e48e",
                "xneName": "e85fe78f8dd5af86202cf381"
            },
            "originalXnec2": {
                "assessedElementMrid": "00ed6a3cd8b97b259bb36163",
                "assessedElementName": "8a9a715a8087a09dae7422e2",
                "biddingZoneCode": "10YBE----------2",
                "conductingEquipmentMrid": "738f1e15b58530ee68fb9e0c",
                "contingencyMrid": "e44fb2182adc95bbe632aaa2",
                "contingencyName": "9e626c2c8319f1c75f5caeb2",
                "fAfter": 58,
                "fBefore": 64,
                "fMax": 62,
                "hasCostlyRa": true,
                "iAfter": 25,
                "iBefore": 34,
                "iMax": 87,
                "id": "282d6166e80f4ac25626d092",
                "raMrid": "a23a7d743e3ebd4d0149ce95",
                "tsoCode": "10X1001A1001A094",
                "xneMrid": "00ed6a3cd8b97b259bb36163",
                "xneName": "8a9a715a8087a09dae7422e2"
            }
        }
    ],
    "crosaProcessType": "01f48fa1769db0f3458c2420",
    "crosaVersion": 1,
    "csProcessVersion": 2,
    "id": "19eca845eb5f31d7874a9854",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "983aaca42b5aa5a69420556b"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult_20250213_D/SelectedXnecResult__file_3.json
{
    "businessDay": "2024-02-23",
    "businessTimestamp": "2024-02-23T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "0ce5ebd4f57168f16cc77478",
            "originalXnec1": {
                "assessedElementMrid": "45619ca03df30dc688c42509",
                "assessedElementName": "dbc298ec74e9b46bd6907673",
                "biddingZoneCode": "10YSK-SEPS-----K",
                "conductingEquipmentMrid": "5ec343344528023d8ef9cd19",
                "contingencyMrid": "459cba83a11339c30ae43642",
                "contingencyName": "264926154af75b0153a20860",
                "fAfter": 39,
                "fBefore": 45,
                "fMax": 43,
                "hasCostlyRa": true,
                "iAfter": 29,
                "iBefore": 42,
                "iMax": 25,
                "id": "23c0f2221ac54154e0c8a413",
                "raMrid": "6a96e393f8264319372c39de",
                "tsoCode": "10XSK-SEPS-GRIDB",
                "xneMrid": "45619ca03df30dc688c42509",
                "xneName": "dbc298ec74e9b46bd6907673"
            },
            "originalXnec2": {
                "assessedElementMrid": "9c52de117e7c805e7ca515b2",
                "assessedElementName": "3dc256b5ed68d9243909ebf9",
                "biddingZoneCode": "10YHR-HEP------M",
                "conductingEquipmentMrid": "a4bfe3e18a6928c21d225450",
                "contingencyMrid": "459cba83a11339c30ae43642",
                "contingencyName": "264926154af75b0153a20860",
                "fAfter": 39,
                "fBefore": 45,
                "fMax": 43,
                "hasCostlyRa": true,
                "iAfter": 29,
                "iBefore": 42,
                "iMax": 25,
                "id": "a32e2246e34526db89ccf336",
                "raMrid": "6a96e393f8264319372c39de",
                "tsoCode": "10XHR-HEP-OPS--A",
                "xneMrid": "9c52de117e7c805e7ca515b2",
                "xneName": "3dc256b5ed68d9243909ebf9"
            }
        }
    ],
    "crosaProcessType": "8e404717247109d901735910",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "45043777774f75aaba241e11",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "c0f81946667d705f6f7f2d32"
}

=== arielmbomakaeyros/como-files/SelectedXnecResult__file_3.json
{
    "businessDay": "2024-05-20",
    "businessTimestamp": "2024-05-20T01:30:00Z",
    "comoDocumentType": "CS_SELECTED_XNEC_RESULT",
    "comoDocumentVersion": "R24Q4V1_0",
    "convertedXnecList": [
        {
            "id": "f24d36c29c27b8f94b94d38e",
            "originalXnec1": {
                "assessedElementMrid": "1f0d5c8aad95c0f1931077e6",
                "assessedElementName": "d10174ccfa6cb0f72601745f",
                "biddingZoneCode": "6f790804e9ce182239b9d8ec",
                "conductingEquipmentMrid": null,
                "contingencyMrid": "bb65d76e0036e8ff6a92368a",
                "contingencyName": null,
                "fAfter": 10.42,
                "fBefore": 12.32,
                "fMax": 41.38,
                "hasCostlyRa": true,
                "iAfter": 94.32,
                "iBefore": 43.47,
                "iMax": 14.44,
                "id": "f930fec3da458a97635b3fb8",
                "raMrid": "fa54a5a131a306a39fded947",
                "tsoCode": "7d7370d28eff7685c7fc44ec",
                "xneMrid": "f1b85f16ce069a563cc40ffd",
                "xneName": "d6ad2521860819ab42a72ac8"
            },
            "originalXnec2": {
                "assessedElementMrid": "2ee5ef6892314fcdfd62ab07",
                "assessedElementName": "15e93bc60af448dd389a66be",
                "biddingZoneCode": "a3d77443279ceb8d817c86da",
                "conductingEquipmentMrid": "1155102a33b7d73215787223",
                "contingencyMrid": "d3441cf214d5e013f520a368",
                "contingencyName": "f109d578e9028754e2156210",
                "fAfter": 72.05,
                "fBefore": 52.7,
                "fMax": 59.63,
                "hasCostlyRa": false,
                "iAfter": 15.25,
                "iBefore": 53.66,
                "iMax": 52.18,
                "id": "a2fd66dcd61b4972ceef569b",
                "raMrid": null,
                "tsoCode": "b1723c0072e6060d3ae4af21",
                "xneMrid": "4b50990ca29c9d715d43b786",
                "xneName": null
            }
        }
    ],
    "crosaProcessType": "28a70600e3e398a83034a1f6",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "id": "dfbbd93ecf171c4080cae3b9",
    "timeHorizon": "dayAhead",
    "xnecSelectionInputId": "80b451d6c2ea0a7ca7ff8be2"
}
