=== arielmbomakaeyros/como-files/ptdf_psdf/MappingTSOdata_IntermediateResultsPerHour_fixed_2.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/MappingTSOdata_IntermediateResultsPerHour",
    "title": "MappingTSOdata_IntermediateResultsPerHour",
    "type": "object",
    "properties": {
        "aggregatedVolumeDownwardCostlyAnora": {
            "type": "number"
        },
        "aggregatedVolumeUpwardCostlyAnora": {
            "type": "number"
        },
        "averageCostDownwardOraOrAnora": {
            "type": "number"
        },
        "averageCostUpwardOraOrAnora": {
            "type": "number"
        },
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessType": {
            "type": "string"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "hourCongested": {
            "type": "boolean"
        },
        "penaltyBalancingSlack": {
            "type": "number"
        },
        "penaltyCostForAnoraVolumes": {
            "type": "number"
        },
        "penaltyFlowSlack": {
            "type": "number"
        },
        "psdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSDFdata"
            }
        },
        "pstData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSTdata"
            }
        },
        "ptdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PTDFdata"
            }
        },
        "raData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/RAdata"
            }
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "totalCostsAllOras": {
            "type": "number"
        },
        "totalCostsAllPsts": {
            "type": "number"
        },
        "xnecData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/XNECdata"
            }
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "PSDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "pstId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "pstId",
                "sensitivity"
            ]
        },
        "PSTdata": {
            "type": "object",
            "properties": {
                "costsPst": {
                    "type": "number"
                },
                "pstId": {
                    "type": "string"
                },
                "tapAfter": {
                    "type": "number"
                },
                "tapBefore": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsPst",
                "pstId",
                "tapAfter",
                "tapBefore"
            ]
        },
        "PTDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "raId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "raId",
                "sensitivity"
            ]
        },
        "RAdata": {
            "type": "object",
            "properties": {
                "costsOra": {
                    "type": "number"
                },
                "costsOraVariable": {
                    "type": "number"
                },
                "hourlyCostsAfterFixedCosts": {
                    "type": "number"
                },
                "hourlyCostsAfterReallocation": {
                    "type": "number"
                },
                "hourlyCostsFiltered": {
                    "type": "number"
                },
                "raId": {
                    "type": "string"
                },
                "variableCostFinal": {
                    "type": "number"
                },
                "variableCostIntermediate": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsOra",
                "costsOraVariable",
                "hourlyCostsAfterFixedCosts",
                "hourlyCostsAfterReallocation",
                "hourlyCostsFiltered",
                "raId",
                "variableCostFinal",
                "variableCostIntermediate"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "XNECdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "fLimit": {
                    "type": "number"
                },
                "fPrimeB": {
                    "type": "number"
                },
                "fWithoutOrasAndPsts": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "fLimit",
                "fPrimeB",
                "fWithoutOrasAndPsts"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "aggregatedVolumeDownwardCostlyAnora",
        "aggregatedVolumeUpwardCostlyAnora",
        "averageCostDownwardOraOrAnora",
        "averageCostUpwardOraOrAnora",
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaVersion",
        "csProcessType",
        "csProcessVersion",
        "hourCongested",
        "penaltyBalancingSlack",
        "penaltyCostForAnoraVolumes",
        "penaltyFlowSlack",
        "timeHorizon",
        "totalCostsAllOras",
        "totalCostsAllPsts"
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_3.json
{
    "aggregatedVolumeDownwardCostlyAnora": 62.53,
    "aggregatedVolumeUpwardCostlyAnora": 57.67,
    "averageCostDownwardOraOrAnora": 44.6,
    "averageCostUpwardOraOrAnora": 2.63,
    "businessDay": "2024-08-15",
    "businessTimestamp": "2024-08-15T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "4402de31b0b2bf7bd6bfc490",
    "csProcessVersion": 1,
    "hourCongested": false,
    "penaltyBalancingSlack": 14.08,
    "penaltyCostForAnoraVolumes": 40.61,
    "penaltyFlowSlack": 47.47,
    "psdfData": [
        {
            "convertedXnecId": "17cf36da-6bb3-4e38-b181-7fb739937d86",
            "pstId": "f2e12fd6-2ac5-4c2a-bc84-403a54394588",
            "sensitivity": 2684.646
        },
        {
            "convertedXnecId": "2688e238-f4d1-4f3e-9555-7a8e9dc558c9",
            "pstId": "1386b722-d59e-47a5-9bb9-136d4ba795cb",
            "sensitivity": 4960.516
        },
        {
            "convertedXnecId": "3d094beb-f431-4a26-aef0-ac698c7a4c85",
            "pstId": "73753a69-0241-4ab7-b67a-b453207d4c74",
            "sensitivity": 1535.597
        },
        {
            "convertedXnecId": "98a0c17a-74d1-495f-9989-78c2414f4037",
            "pstId": "f71ced06-443b-4f6d-86a3-421155843b11",
            "sensitivity": 115.223
        },
        {
            "convertedXnecId": "a047eeba-71e9-408a-98d7-61eb9fb7faf7",
            "pstId": "ded3df42-1dfc-4bf7-86aa-9aa8202ca01c",
            "sensitivity": 4447.916
        }
    ],
    "pstData": [
        {
            "costsPst": 177.44,
            "pstId": "f2e12fd6-2ac5-4c2a-bc84-403a54394588",
            "tapAfter": 26.62,
            "tapBefore": 193.37
        },
        {
            "costsPst": 192.29,
            "pstId": "1386b722-d59e-47a5-9bb9-136d4ba795cb",
            "tapAfter": 37.48,
            "tapBefore": 189.3
        },
        {
            "costsPst": 154.58,
            "pstId": "73753a69-0241-4ab7-b67a-b453207d4c74",
            "tapAfter": 50.03,
            "tapBefore": 157.14
        },
        {
            "costsPst": 190.72,
            "pstId": "f71ced06-443b-4f6d-86a3-421155843b11",
            "tapAfter": 48.56,
            "tapBefore": 167.98
        },
        {
            "costsPst": 180.98,
            "pstId": "ded3df42-1dfc-4bf7-86aa-9aa8202ca01c",
            "tapAfter": 78.5,
            "tapBefore": 178.24
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "40ffe5ac-2120-4cd8-9164-5e9234d3582e",
            "raId": "20240409_DA_CROSA_ORA_1872",
            "sensitivity": 0.934
        },
        {
            "convertedXnecId": "311e8d29-51f6-48d6-b834-02f0c20c90ef",
            "raId": "20240509_DA_CROSA_ORA_7202",
            "sensitivity": 0.762
        },
        {
            "convertedXnecId": "c3013ee9-bd7a-4b4f-be70-f996bf1e0625",
            "raId": "20240124_DA_CROSA_ORA_7616",
            "sensitivity": 0.026
        },
        {
            "convertedXnecId": "8a0700f4-08b0-4db3-a798-a840bda6e311",
            "raId": "20240407_DA_CROSA_ORA_5978",
            "sensitivity": 0.054
        },
        {
            "convertedXnecId": "6cdea79b-5a0f-453c-909c-92e763300d9b",
            "raId": "20241111_DA_CROSA_ORA_6722",
            "sensitivity": 0.41
        }
    ],
    "raData": [
        {
            "costsOra": 167.71,
            "costsOraVariable": 189.11,
            "hourlyCostsAfterFixedCosts": 169.06,
            "hourlyCostsAfterReallocation": 171.31,
            "hourlyCostsFiltered": 4.61,
            "raId": "20240409_DA_CROSA_ORA_1872",
            "variableCostFinal": 167.5,
            "variableCostIntermediate": 179.63
        },
        {
            "costsOra": 188.94,
            "costsOraVariable": 194.17,
            "hourlyCostsAfterFixedCosts": 196.19,
            "hourlyCostsAfterReallocation": 153.99,
            "hourlyCostsFiltered": 16.43,
            "raId": "20240509_DA_CROSA_ORA_7202",
            "variableCostFinal": 177.44,
            "variableCostIntermediate": 194.04
        },
        {
            "costsOra": 156.14,
            "costsOraVariable": 154.98,
            "hourlyCostsAfterFixedCosts": 170.95,
            "hourlyCostsAfterReallocation": 159.46,
            "hourlyCostsFiltered": 85.58,
            "raId": "20240124_DA_CROSA_ORA_7616",
            "variableCostFinal": 196.7,
            "variableCostIntermediate": 194.63
        },
        {
            "costsOra": 165.14,
            "costsOraVariable": 167.84,
            "hourlyCostsAfterFixedCosts": 170.73,
            "hourlyCostsAfterReallocation": 198.04,
            "hourlyCostsFiltered": 26.42,
            "raId": "20240407_DA_CROSA_ORA_5978",
            "variableCostFinal": 160.33,
            "variableCostIntermediate": 186.52
        },
        {
            "costsOra": 152.1,
            "costsOraVariable": 199.46,
            "hourlyCostsAfterFixedCosts": 159.72,
            "hourlyCostsAfterReallocation": 187.19,
            "hourlyCostsFiltered": 36.1,
            "raId": "20241111_DA_CROSA_ORA_6722",
            "variableCostFinal": 155.24,
            "variableCostIntermediate": 156.09
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 830.03,
    "totalCostsAllPsts": 896.01,
    "xnecData": [
        {
            "convertedXnecId": "17cf36da-6bb3-4e38-b181-7fb739937d86",
            "fLimit": 35.17,
            "fPrimeB": 99.34,
            "fWithoutOrasAndPsts": 67.25
        },
        {
            "convertedXnecId": "2688e238-f4d1-4f3e-9555-7a8e9dc558c9",
            "fLimit": 38.83,
            "fPrimeB": 82.0,
            "fWithoutOrasAndPsts": 60.41
        },
        {
            "convertedXnecId": "3d094beb-f431-4a26-aef0-ac698c7a4c85",
            "fLimit": 33.34,
            "fPrimeB": 89.27,
            "fWithoutOrasAndPsts": 61.3
        },
        {
            "convertedXnecId": "98a0c17a-74d1-495f-9989-78c2414f4037",
            "fLimit": 43.79,
            "fPrimeB": 86.38,
            "fWithoutOrasAndPsts": 65.08
        },
        {
            "convertedXnecId": "a047eeba-71e9-408a-98d7-61eb9fb7faf7",
            "fLimit": 41.56,
            "fPrimeB": 81.04,
            "fWithoutOrasAndPsts": 61.3
        },
        {
            "convertedXnecId": "40ffe5ac-2120-4cd8-9164-5e9234d3582e",
            "fLimit": 42.54,
            "fPrimeB": 82.58,
            "fWithoutOrasAndPsts": 62.56
        },
        {
            "convertedXnecId": "311e8d29-51f6-48d6-b834-02f0c20c90ef",
            "fLimit": 46.46,
            "fPrimeB": 92.37,
            "fWithoutOrasAndPsts": 69.42
        },
        {
            "convertedXnecId": "c3013ee9-bd7a-4b4f-be70-f996bf1e0625",
            "fLimit": 48.59,
            "fPrimeB": 98.54,
            "fWithoutOrasAndPsts": 73.56
        },
        {
            "convertedXnecId": "8a0700f4-08b0-4db3-a798-a840bda6e311",
            "fLimit": 35.78,
            "fPrimeB": 88.15,
            "fWithoutOrasAndPsts": 61.97
        },
        {
            "convertedXnecId": "6cdea79b-5a0f-453c-909c-92e763300d9b",
            "fLimit": 41.52,
            "fPrimeB": 80.96,
            "fWithoutOrasAndPsts": 61.24
        }
    ]
}

=== arielmbomakaeyros/como-files/ptdf_psdf/example.json
{
  "aggregatedVolumeDownwardCostlyAnora": 2653.09,
  "aggregatedVolumeUpwardCostlyAnora": 2005.09,
  "averageCostDownwardOraOrAnora": 198.81,
  "averageCostUpwardOraOrAnora": 218.77,
  "businessTimestamp": "2024-10-01T00:30:00Z",
  "businessDay": "2024-10-01",
  "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
  "comoDocumentVersion": "R24Q4V1_0",
  "crosaVersion": 5,
  "csProcessType": "crosaId1",
  "csProcessVersion": 3,
  "hourCongested": true,
  "penaltyBalancingSlack": 22,
  "penaltyCostForAnoraVolumes": 0,
  "penaltyFlowSlack": 233,
  "timeHorizon": "intraday",
  "totalCostsAllOras": 13401.56,
  "totalCostsAllPsts": 10001.1,
  "psdfData": [
    {
      "convertedXnecId": "596a0eedc2d60451755ae6c8",
      "pstId": "pstId-1",
      "sensitivity": -14.538
    }
  ],
  "pstData": [
    {
      "costsPst": 120.3,
      "pstId": "pstId-1",
      "tapAfter": 10.5,
      "tapBefore": 13
    }
  ],
  "ptdfData": [
    {
      "convertedXnecId": "c0da9301c97b1a8b335e0d42",
      "raId": "20220227_DA_CROSA_ORA_0601",
      "sensitivity": 1.212
    }
  ],
  "raData": [
    {
      "costsOra": 13401.56,
      "costsOraVariable": 3401.56,
      "hourlyCostsAfterFixedCosts": 10000,
      "hourlyCostsAfterReallocation": 13401.56,
      "hourlyCostsFiltered": 100,
      "raId": "20220227_DA_CROSA_ORA_0601",
      "variableCostFinal": 13401.56,
      "variableCostIntermediate": 10400.56
    }
  ],
  "xnecData": [
    {
      "convertedXnecId": "c0da9301c97b1a8b335e0d42",
      "fLimit": 122,
      "fPrimeB": 130,
      "fWithoutOrasAndPsts": 140
    },
    {
      "convertedXnecId": "596a0eedc2d60451755ae6c8",
      "fLimit": 120,
      "fPrimeB": 110,
      "fWithoutOrasAndPsts": 120
    }
  ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_1.json
{
    "aggregatedVolumeDownwardCostlyAnora": 62.12,
    "aggregatedVolumeUpwardCostlyAnora": 82.61,
    "averageCostDownwardOraOrAnora": 15.57,
    "averageCostUpwardOraOrAnora": 91.74,
    "businessDay": "2024-03-26",
    "businessTimestamp": "2024-03-26T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "0f166630c2b13a4ac80fd6b5",
    "csProcessVersion": 1,
    "hourCongested": false,
    "penaltyBalancingSlack": 62.35,
    "penaltyCostForAnoraVolumes": 11.13,
    "penaltyFlowSlack": 66.07,
    "psdfData": [
        {
            "convertedXnecId": "477f97e4-1fbd-4d24-9175-2a758662fe2e",
            "pstId": "20241004_DA_CROSA_ORA_9427",
            "sensitivity": 5198.996
        },
        {
            "convertedXnecId": "4476e748-844f-4a87-b992-aebcbe27be76",
            "pstId": "20240408_DA_CROSA_ORA_5731",
            "sensitivity": 681.951
        },
        {
            "convertedXnecId": "90ccf897-7702-4bcc-8ee8-b1698211dd23",
            "pstId": "20240805_DA_CROSA_ORA_3345",
            "sensitivity": 2180.366
        },
        {
            "convertedXnecId": "0ad0539a-a9cc-4622-889d-dad4ce858910",
            "pstId": "20250113_DA_CROSA_ORA_7656",
            "sensitivity": 262.721
        },
        {
            "convertedXnecId": "0eec5938-660c-4606-b206-2dcf88d53991",
            "pstId": "20240503_DA_CROSA_ORA_1551",
            "sensitivity": 1908.98
        }
    ],
    "pstData": [
        {
            "costsPst": 198.5,
            "pstId": "20241004_DA_CROSA_ORA_9427",
            "tapAfter": 1.75,
            "tapBefore": 193.0
        },
        {
            "costsPst": 169.63,
            "pstId": "20240408_DA_CROSA_ORA_5731",
            "tapAfter": 33.5,
            "tapBefore": 154.86
        },
        {
            "costsPst": 186.98,
            "pstId": "20240805_DA_CROSA_ORA_3345",
            "tapAfter": 43.11,
            "tapBefore": 170.03
        },
        {
            "costsPst": 176.24,
            "pstId": "20250113_DA_CROSA_ORA_7656",
            "tapAfter": 9.53,
            "tapBefore": 158.44
        },
        {
            "costsPst": 177.32,
            "pstId": "20240503_DA_CROSA_ORA_1551",
            "tapAfter": 77.32,
            "tapBefore": 162.29
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "45b7e57f-8c43-4aba-996e-122c5773e998",
            "raId": "20240131_DA_CROSA_ORA_2332",
            "sensitivity": 0.577
        },
        {
            "convertedXnecId": "e9edb69a-e2d2-4c42-b83d-b7ce0522a936",
            "raId": "20241116_DA_CROSA_ORA_6597",
            "sensitivity": 0.003
        }
    ],
    "raData": [
        {
            "costsOra": 152.9,
            "costsOraVariable": 187.1,
            "hourlyCostsAfterFixedCosts": 182.31,
            "hourlyCostsAfterReallocation": 150.63,
            "hourlyCostsFiltered": 43.9,
            "raId": "20240131_DA_CROSA_ORA_2332",
            "variableCostFinal": 178.61,
            "variableCostIntermediate": 161.84
        },
        {
            "costsOra": 197.08,
            "costsOraVariable": 180.15,
            "hourlyCostsAfterFixedCosts": 198.9,
            "hourlyCostsAfterReallocation": 199.67,
            "hourlyCostsFiltered": 79.5,
            "raId": "20241116_DA_CROSA_ORA_6597",
            "variableCostFinal": 189.41,
            "variableCostIntermediate": 178.75
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 349.98,
    "totalCostsAllPsts": 908.67,
    "xnecData": [
        {
            "convertedXnecId": "477f97e4-1fbd-4d24-9175-2a758662fe2e",
            "fLimit": 40.56,
            "fPrimeB": 84.48,
            "fWithoutOrasAndPsts": 62.52
        },
        {
            "convertedXnecId": "4476e748-844f-4a87-b992-aebcbe27be76",
            "fLimit": 36.63,
            "fPrimeB": 96.36,
            "fWithoutOrasAndPsts": 66.5
        },
        {
            "convertedXnecId": "90ccf897-7702-4bcc-8ee8-b1698211dd23",
            "fLimit": 35.42,
            "fPrimeB": 83.74,
            "fWithoutOrasAndPsts": 59.58
        },
        {
            "convertedXnecId": "0ad0539a-a9cc-4622-889d-dad4ce858910",
            "fLimit": 40.17,
            "fPrimeB": 89.8,
            "fWithoutOrasAndPsts": 64.98
        },
        {
            "convertedXnecId": "0eec5938-660c-4606-b206-2dcf88d53991",
            "fLimit": 39.9,
            "fPrimeB": 95.16,
            "fWithoutOrasAndPsts": 67.53
        },
        {
            "convertedXnecId": "45b7e57f-8c43-4aba-996e-122c5773e998",
            "fLimit": 34.71,
            "fPrimeB": 95.15,
            "fWithoutOrasAndPsts": 64.93
        },
        {
            "convertedXnecId": "e9edb69a-e2d2-4c42-b83d-b7ce0522a936",
            "fLimit": 47.35,
            "fPrimeB": 94.32,
            "fWithoutOrasAndPsts": 70.83
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_10.json
{
    "aggregatedVolumeDownwardCostlyAnora": 47.83,
    "aggregatedVolumeUpwardCostlyAnora": 28.32,
    "averageCostDownwardOraOrAnora": 66.33,
    "averageCostUpwardOraOrAnora": 34.9,
    "businessDay": "2024-06-14",
    "businessTimestamp": "2024-06-14T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "07e90e55b5d2d12c98fdcf92",
    "csProcessVersion": 4,
    "hourCongested": false,
    "penaltyBalancingSlack": 88.7,
    "penaltyCostForAnoraVolumes": 71.16,
    "penaltyFlowSlack": 10.7,
    "psdfData": [
        {
            "convertedXnecId": "d14a044a-1cea-4b83-8234-357187f9646e",
            "pstId": "20240406_DA_CROSA_ORA_3589",
            "sensitivity": 482.465
        },
        {
            "convertedXnecId": "2fe13949-52f7-4531-8db8-c5fc680e225d",
            "pstId": "20241130_DA_CROSA_ORA_7365",
            "sensitivity": 134.486
        },
        {
            "convertedXnecId": "6e7eaa49-4a25-406d-b256-8e9200cfcf46",
            "pstId": "20240127_DA_CROSA_ORA_8442",
            "sensitivity": 4685.675
        },
        {
            "convertedXnecId": "9df6bdde-4417-4ede-97ae-52aed64fe92b",
            "pstId": "20241123_DA_CROSA_ORA_3624",
            "sensitivity": 3312.565
        },
        {
            "convertedXnecId": "4a8827e5-7409-4af1-8e67-1d323263e8ef",
            "pstId": "20241009_DA_CROSA_ORA_1019",
            "sensitivity": 2012.205
        }
    ],
    "pstData": [
        {
            "costsPst": 190.59,
            "pstId": "20240406_DA_CROSA_ORA_3589",
            "tapAfter": 64.35,
            "tapBefore": 199.09
        },
        {
            "costsPst": 159.79,
            "pstId": "20241130_DA_CROSA_ORA_7365",
            "tapAfter": 95.19,
            "tapBefore": 162.99
        },
        {
            "costsPst": 188.9,
            "pstId": "20240127_DA_CROSA_ORA_8442",
            "tapAfter": 4.22,
            "tapBefore": 153.43
        },
        {
            "costsPst": 190.31,
            "pstId": "20241123_DA_CROSA_ORA_3624",
            "tapAfter": 47.87,
            "tapBefore": 176.26
        },
        {
            "costsPst": 198.28,
            "pstId": "20241009_DA_CROSA_ORA_1019",
            "tapAfter": 29.72,
            "tapBefore": 163.85
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "189f936c-9973-4963-ba4c-713f45ebf422",
            "raId": "20240122_DA_CROSA_ORA_1744",
            "sensitivity": 0.642
        },
        {
            "convertedXnecId": "a807fa06-b81c-4f33-b8db-9a34a5865b41",
            "raId": "20240628_DA_CROSA_ORA_8895",
            "sensitivity": 0.14
        },
        {
            "convertedXnecId": "5b6382e9-83c8-452d-9160-2989f76f50e9",
            "raId": "20240507_DA_CROSA_ORA_8891",
            "sensitivity": 0.939
        },
        {
            "convertedXnecId": "c8d2ddee-cce7-4b6a-912e-ff9114fe7fda",
            "raId": "20240905_DA_CROSA_ORA_7789",
            "sensitivity": 0.602
        }
    ],
    "raData": [
        {
            "costsOra": 154.71,
            "costsOraVariable": 199.83,
            "hourlyCostsAfterFixedCosts": 166.42,
            "hourlyCostsAfterReallocation": 192.02,
            "hourlyCostsFiltered": 3.66,
            "raId": "20240122_DA_CROSA_ORA_1744",
            "variableCostFinal": 152.63,
            "variableCostIntermediate": 190.09
        },
        {
            "costsOra": 166.61,
            "costsOraVariable": 180.29,
            "hourlyCostsAfterFixedCosts": 153.04,
            "hourlyCostsAfterReallocation": 168.1,
            "hourlyCostsFiltered": 61.87,
            "raId": "20240628_DA_CROSA_ORA_8895",
            "variableCostFinal": 167.97,
            "variableCostIntermediate": 178.75
        },
        {
            "costsOra": 192.91,
            "costsOraVariable": 156.77,
            "hourlyCostsAfterFixedCosts": 160.99,
            "hourlyCostsAfterReallocation": 194.06,
            "hourlyCostsFiltered": 16.84,
            "raId": "20240507_DA_CROSA_ORA_8891",
            "variableCostFinal": 159.64,
            "variableCostIntermediate": 192.4
        },
        {
            "costsOra": 150.63,
            "costsOraVariable": 197.63,
            "hourlyCostsAfterFixedCosts": 167.9,
            "hourlyCostsAfterReallocation": 194.6,
            "hourlyCostsFiltered": 66.66,
            "raId": "20240905_DA_CROSA_ORA_7789",
            "variableCostFinal": 170.56,
            "variableCostIntermediate": 198.19
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 664.86,
    "totalCostsAllPsts": 927.87,
    "xnecData": [
        {
            "convertedXnecId": "d14a044a-1cea-4b83-8234-357187f9646e",
            "fLimit": 42.79,
            "fPrimeB": 96.9,
            "fWithoutOrasAndPsts": 69.84
        },
        {
            "convertedXnecId": "2fe13949-52f7-4531-8db8-c5fc680e225d",
            "fLimit": 30.15,
            "fPrimeB": 85.17,
            "fWithoutOrasAndPsts": 57.66
        },
        {
            "convertedXnecId": "6e7eaa49-4a25-406d-b256-8e9200cfcf46",
            "fLimit": 31.1,
            "fPrimeB": 85.24,
            "fWithoutOrasAndPsts": 58.17
        },
        {
            "convertedXnecId": "9df6bdde-4417-4ede-97ae-52aed64fe92b",
            "fLimit": 39.09,
            "fPrimeB": 81.81,
            "fWithoutOrasAndPsts": 60.45
        },
        {
            "convertedXnecId": "4a8827e5-7409-4af1-8e67-1d323263e8ef",
            "fLimit": 44.1,
            "fPrimeB": 85.4,
            "fWithoutOrasAndPsts": 64.75
        },
        {
            "convertedXnecId": "189f936c-9973-4963-ba4c-713f45ebf422",
            "fLimit": 38.61,
            "fPrimeB": 84.98,
            "fWithoutOrasAndPsts": 61.8
        },
        {
            "convertedXnecId": "a807fa06-b81c-4f33-b8db-9a34a5865b41",
            "fLimit": 37.91,
            "fPrimeB": 95.42,
            "fWithoutOrasAndPsts": 66.66
        },
        {
            "convertedXnecId": "5b6382e9-83c8-452d-9160-2989f76f50e9",
            "fLimit": 33.24,
            "fPrimeB": 86.22,
            "fWithoutOrasAndPsts": 59.73
        },
        {
            "convertedXnecId": "c8d2ddee-cce7-4b6a-912e-ff9114fe7fda",
            "fLimit": 43.61,
            "fPrimeB": 96.49,
            "fWithoutOrasAndPsts": 70.05
        }
    ]
}
