=== arielmbomakaeyros/como-files/ptdf_psdf/MappingTSOdata_IntermediateResultsPerHour_fixed_2.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/MappingTSOdata_IntermediateResultsPerHour",
    "title": "MappingTSOdata_IntermediateResultsPerHour",
    "type": "object",
    "properties": {
        "aggregatedVolumeDownwardCostlyAnora": {
            "type": "number"
        },
        "aggregatedVolumeUpwardCostlyAnora": {
            "type": "number"
        },
        "averageCostDownwardOraOrAnora": {
            "type": "number"
        },
        "averageCostUpwardOraOrAnora": {
            "type": "number"
        },
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessType": {
            "type": "string"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "hourCongested": {
            "type": "boolean"
        },
        "penaltyBalancingSlack": {
            "type": "number"
        },
        "penaltyCostForAnoraVolumes": {
            "type": "number"
        },
        "penaltyFlowSlack": {
            "type": "number"
        },
        "psdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSDFdata"
            }
        },
        "pstData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSTdata"
            }
        },
        "ptdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PTDFdata"
            }
        },
        "raData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/RAdata"
            }
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "totalCostsAllOras": {
            "type": "number"
        },
        "totalCostsAllPsts": {
            "type": "number"
        },
        "xnecData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/XNECdata"
            }
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "PSDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "pstId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "pstId",
                "sensitivity"
            ]
        },
        "PSTdata": {
            "type": "object",
            "properties": {
                "costsPst": {
                    "type": "number"
                },
                "pstId": {
                    "type": "string"
                },
                "tapAfter": {
                    "type": "number"
                },
                "tapBefore": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsPst",
                "pstId",
                "tapAfter",
                "tapBefore"
            ]
        },
        "PTDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "raId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "raId",
                "sensitivity"
            ]
        },
        "RAdata": {
            "type": "object",
            "properties": {
                "costsOra": {
                    "type": "number"
                },
                "costsOraVariable": {
                    "type": "number"
                },
                "hourlyCostsAfterFixedCosts": {
                    "type": "number"
                },
                "hourlyCostsAfterReallocation": {
                    "type": "number"
                },
                "hourlyCostsFiltered": {
                    "type": "number"
                },
                "raId": {
                    "type": "string"
                },
                "variableCostFinal": {
                    "type": "number"
                },
                "variableCostIntermediate": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsOra",
                "costsOraVariable",
                "hourlyCostsAfterFixedCosts",
                "hourlyCostsAfterReallocation",
                "hourlyCostsFiltered",
                "raId",
                "variableCostFinal",
                "variableCostIntermediate"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "XNECdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "fLimit": {
                    "type": "number"
                },
                "fPrimeB": {
                    "type": "number"
                },
                "fWithoutOrasAndPsts": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "fLimit",
                "fPrimeB",
                "fWithoutOrasAndPsts"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "aggregatedVolumeDownwardCostlyAnora",
        "aggregatedVolumeUpwardCostlyAnora",
        "averageCostDownwardOraOrAnora",
        "averageCostUpwardOraOrAnora",
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaVersion",
        "csProcessType",
        "csProcessVersion",
        "hourCongested",
        "penaltyBalancingSlack",
        "penaltyCostForAnoraVolumes",
        "penaltyFlowSlack",
        "timeHorizon",
        "totalCostsAllOras",
        "totalCostsAllPsts"
    ]
}

=== arielmbomakaeyros/como-files/2MappingTSOdata_IntermediateResultsPerHour__file_1 copy 2.json
{
    "aggregatedVolumeDownwardCostlyAnora": 50.18,
    "aggregatedVolumeUpwardCostlyAnora": 67.11,
    "averageCostDownwardOraOrAnora": 23.08,
    "averageCostUpwardOraOrAnora": 3.13,
    "businessDay": "2024-09-30",
    "businessTimestamp": "2024-09-30T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "b7163c1fff0b1f5c59ebf87a",
    "csProcessVersion": 5,
    "hourCongested": true,
    "penaltyBalancingSlack": 58.71,
    "penaltyCostForAnoraVolumes": 20.51,
    "penaltyFlowSlack": 41.77,
    "psdfData": [
        {
            "convertedXnecId": "69df0d01-1ac2-4399-9fa3-56e71c63427a",
            "pstId": "20240627_DA_CROSA_ORA_6169",
            "sensitivity": 1236.354
        }
    ],
    "pstData": [
        {
            "costsPst": 198.21,
            "pstId": "20240627_DA_CROSA_ORA_6169",
            "tapAfter": 54.82,
            "tapBefore": 170.99
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "a427a4ca-1f10-4e73-b249-ed7a64e75f80",
            "raId": "20250104_DA_CROSA_ORA_2112",
            "sensitivity": 0.782
        }
    ],
    "raData": [
        {
            "costsOra": 151.84,
            "costsOraVariable": 164.52,
            "hourlyCostsAfterFixedCosts": 186.62,
            "hourlyCostsAfterReallocation": 186.1,
            "hourlyCostsFiltered": 71.88,
            "raId": "20250104_DA_CROSA_ORA_2112",
            "variableCostFinal": 176.87,
            "variableCostIntermediate": 186.93
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 151.84,
    "totalCostsAllPsts": 198.21,
    "xnecData": [
        {
            "convertedXnecId": "69df0d01-1ac2-4399-9fa3-56e71c63427a",
            "fLimit": 32.53,
            "fPrimeB": 89.2,
            "fWithoutOrasAndPsts": 60.87
        },
        {
            "convertedXnecId": "a427a4ca-1f10-4e73-b249-ed7a64e75f80",
            "fLimit": 44.04,
            "fPrimeB": 91.05,
            "fWithoutOrasAndPsts": 67.55
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_5.json
{
    "aggregatedVolumeDownwardCostlyAnora": 11.9,
    "aggregatedVolumeUpwardCostlyAnora": 18.84,
    "averageCostDownwardOraOrAnora": 13.27,
    "averageCostUpwardOraOrAnora": 69.27,
    "businessDay": "2024-12-08",
    "businessTimestamp": "2024-12-08T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "574a72b1c5599c538edbdee7",
    "csProcessVersion": 3,
    "hourCongested": true,
    "penaltyBalancingSlack": 56.72,
    "penaltyCostForAnoraVolumes": 12.73,
    "penaltyFlowSlack": 83.8,
    "psdfData": {
        "convertedXnecId": "b9fe2db9-afe9-4f69-b530-f71710d6cf6f",
        "raId": "19716f72-aefa-4d9f-b00f-576635b9bc51",
        "sensitivity": 30356.267440794454
    },
    "pstData": [
        {
            "costsPst": 96.41,
            "pstId": "4a3092b4698f3609287b46cb",
            "tapAfter": 99.98,
            "tapBefore": 21.3
        }
    ],
    "ptdfData": {
        "convertedXnecId": "e10f890c-d35d-4f2c-9838-fd82181d44c0",
        "raId": "c7e4d695-e6ee-442d-b5fa-0f44f76a016b",
        "sensitivity": 1.8
    },
    "raData": [
        {
            "costsOra": 193.81,
            "costsOraVariable": 197.06,
            "hourlyCostsAfterFixedCosts": 182.56,
            "hourlyCostsAfterReallocation": 199.77,
            "hourlyCostsFiltered": 22.08,
            "raId": "6b648b16-1c70-46f4-b90b-ee862a14d5dd",
            "variableCostFinal": 169.25,
            "variableCostIntermediate": 192.45
        },
        {
            "costsOra": 165.21,
            "costsOraVariable": 167.21,
            "hourlyCostsAfterFixedCosts": 179.55,
            "hourlyCostsAfterReallocation": 198.13,
            "hourlyCostsFiltered": 12.38,
            "raId": "50cc8cd1-0046-4c25-9013-76eae000134f",
            "variableCostFinal": 175.18,
            "variableCostIntermediate": 179.53
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 359.02,
    "totalCostsAllPsts": 6.09,
    "xnecData": [
        {
            "convertedXnecId": "652ecb5b91874a411d6ac3c2",
            "fLimit": 58.99,
            "fPrimeB": 23.63,
            "fWithoutOrasAndPsts": 18.68
        }
    ]
}
