=== arielmbomakaeyros/como-files/ptdf_psdf/MappingTSOdata_IntermediateResultsPerHour_fixed_2.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/MappingTSOdata_IntermediateResultsPerHour",
    "title": "MappingTSOdata_IntermediateResultsPerHour",
    "type": "object",
    "properties": {
        "aggregatedVolumeDownwardCostlyAnora": {
            "type": "number"
        },
        "aggregatedVolumeUpwardCostlyAnora": {
            "type": "number"
        },
        "averageCostDownwardOraOrAnora": {
            "type": "number"
        },
        "averageCostUpwardOraOrAnora": {
            "type": "number"
        },
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "businessTimestamp": {
            "description": "Business timestamp (MTU) in UTC. Use the \"date-time\" format to interpret this.",
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessType": {
            "type": "string"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "hourCongested": {
            "type": "boolean"
        },
        "penaltyBalancingSlack": {
            "type": "number"
        },
        "penaltyCostForAnoraVolumes": {
            "type": "number"
        },
        "penaltyFlowSlack": {
            "type": "number"
        },
        "psdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSDFdata"
            }
        },
        "pstData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PSTdata"
            }
        },
        "ptdfData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PTDFdata"
            }
        },
        "raData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/RAdata"
            }
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "totalCostsAllOras": {
            "type": "number"
        },
        "totalCostsAllPsts": {
            "type": "number"
        },
        "xnecData": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/XNECdata"
            }
        }
    },
    "definitions": {
        "DocumentTypeKind": {
            "type": "string",
            "const": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "PSDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "pstId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "pstId",
                "sensitivity"
            ]
        },
        "PSTdata": {
            "type": "object",
            "properties": {
                "costsPst": {
                    "type": "number"
                },
                "pstId": {
                    "type": "string"
                },
                "tapAfter": {
                    "type": "number"
                },
                "tapBefore": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsPst",
                "pstId",
                "tapAfter",
                "tapBefore"
            ]
        },
        "PTDFdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "raId": {
                    "type": "string"
                },
                "sensitivity": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "raId",
                "sensitivity"
            ]
        },
        "RAdata": {
            "type": "object",
            "properties": {
                "costsOra": {
                    "type": "number"
                },
                "costsOraVariable": {
                    "type": "number"
                },
                "hourlyCostsAfterFixedCosts": {
                    "type": "number"
                },
                "hourlyCostsAfterReallocation": {
                    "type": "number"
                },
                "hourlyCostsFiltered": {
                    "type": "number"
                },
                "raId": {
                    "type": "string"
                },
                "variableCostFinal": {
                    "type": "number"
                },
                "variableCostIntermediate": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "costsOra",
                "costsOraVariable",
                "hourlyCostsAfterFixedCosts",
                "hourlyCostsAfterReallocation",
                "hourlyCostsFiltered",
                "raId",
                "variableCostFinal",
                "variableCostIntermediate"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "XNECdata": {
            "type": "object",
            "properties": {
                "convertedXnecId": {
                    "type": "string"
                },
                "fLimit": {
                    "type": "number"
                },
                "fPrimeB": {
                    "type": "number"
                },
                "fWithoutOrasAndPsts": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "convertedXnecId",
                "fLimit",
                "fPrimeB",
                "fWithoutOrasAndPsts"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "aggregatedVolumeDownwardCostlyAnora",
        "aggregatedVolumeUpwardCostlyAnora",
        "averageCostDownwardOraOrAnora",
        "averageCostUpwardOraOrAnora",
        "businessDay",
        "businessTimestamp",
        "comoDocumentType",
        "comoDocumentVersion",
        "crosaVersion",
        "csProcessType",
        "csProcessVersion",
        "hourCongested",
        "penaltyBalancingSlack",
        "penaltyCostForAnoraVolumes",
        "penaltyFlowSlack",
        "timeHorizon",
        "totalCostsAllOras",
        "totalCostsAllPsts"
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_2.json
{
    "aggregatedVolumeDownwardCostlyAnora": 94.05,
    "aggregatedVolumeUpwardCostlyAnora": 85.98,
    "averageCostDownwardOraOrAnora": 40.74,
    "averageCostUpwardOraOrAnora": 81.1,
    "businessDay": "2025-01-01",
    "businessTimestamp": "2025-01-01T02:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "2122f4a869c3b3e4e66952b5",
    "csProcessVersion": 1,
    "hourCongested": false,
    "penaltyBalancingSlack": 33.36,
    "penaltyCostForAnoraVolumes": 58.77,
    "penaltyFlowSlack": 95.72,
    "psdfData": {
        "convertedXnecId": "7d29cf1d-0a04-4449-bef5-f3dff6167744",
        "raId": "2f5f9848-846c-4aba-beec-c7674209b305",
        "sensitivity": 377972.7944517352
    },
    "pstData": [
        {
            "costsPst": 66.11,
            "pstId": "a085daa355879ba102815422",
            "tapAfter": 99.77,
            "tapBefore": 91.28
        }
    ],
    "ptdfData": {
        "convertedXnecId": "51e9b882-3ffa-4729-9673-590af9be715e",
        "raId": "5b9902bc-26ac-4ec6-bc73-4eb861ed8583",
        "sensitivity": 2.54
    },
    "raData": [
        {
            "costsOra": 156.79,
            "costsOraVariable": 177.51,
            "hourlyCostsAfterFixedCosts": 194.03,
            "hourlyCostsAfterReallocation": 150.27,
            "hourlyCostsFiltered": 53.06,
            "raId": "46609751-f515-434c-897b-0f8476850678",
            "variableCostFinal": 174.29,
            "variableCostIntermediate": 195.19
        },
        {
            "costsOra": 195.69,
            "costsOraVariable": 183.19,
            "hourlyCostsAfterFixedCosts": 181.63,
            "hourlyCostsAfterReallocation": 177.06,
            "hourlyCostsFiltered": 40.9,
            "raId": "ff8d5d3f-0a43-4e2e-84d9-c81fa74f98e9",
            "variableCostFinal": 151.56,
            "variableCostIntermediate": 178.55
        },
        {
            "costsOra": 158.58,
            "costsOraVariable": 186.85,
            "hourlyCostsAfterFixedCosts": 193.1,
            "hourlyCostsAfterReallocation": 161.47,
            "hourlyCostsFiltered": 96.34,
            "raId": "f1a5b19a-7c62-48d8-8a6e-ced07acdaa56",
            "variableCostFinal": 158.03,
            "variableCostIntermediate": 175.9
        },
        {
            "costsOra": 195.07,
            "costsOraVariable": 152.36,
            "hourlyCostsAfterFixedCosts": 170.6,
            "hourlyCostsAfterReallocation": 152.87,
            "hourlyCostsFiltered": 52.63,
            "raId": "d9d517cf-8b97-49d6-8f1c-2f070354d220",
            "variableCostFinal": 199.8,
            "variableCostIntermediate": 194.62
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 706.1300000000001,
    "totalCostsAllPsts": 84.1,
    "xnecData": [
        {
            "convertedXnecId": "e5005a66f9f711e66c077d41",
            "fLimit": 16.93,
            "fPrimeB": 17.46,
            "fWithoutOrasAndPsts": 6.39
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour__file_1 copy.json
{
    "aggregatedVolumeDownwardCostlyAnora": 50.77,
    "aggregatedVolumeUpwardCostlyAnora": 76.8,
    "averageCostDownwardOraOrAnora": 83.15,
    "averageCostUpwardOraOrAnora": 26.96,
    "businessDay": "2024-06-13",
    "businessTimestamp": "2024-06-13T02:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "2860e10d32b4f65cd02c7c2d",
    "csProcessVersion": 3,
    "hourCongested": true,
    "penaltyBalancingSlack": 72.43,
    "penaltyCostForAnoraVolumes": 52.75,
    "penaltyFlowSlack": 66.31,
    "psdfData": [
        {
            "convertedXnecId": "f84960b9-73a8-4794-b19d-6cf4fcd16d2b",
            "pstId": "20250105_DA_CROSA_ORA_8268",
            "sensitivity": 738.565
        },
        {
            "convertedXnecId": "5dfd5c91-a353-4ca2-aba8-289b35f1c740",
            "pstId": "20240429_DA_CROSA_ORA_6989",
            "sensitivity": 190.821
        }
    ],
    "pstData": [
        {
            "costsPst": 197.93,
            "pstId": "6a17dec5-75ec-4ca5-90e5-655e56765956",
            "tapAfter": 39.78,
            "tapBefore": 196.0
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "ed8fd509-c2a6-4bdf-b404-8c8301f98030",
            "raId": "20240817_DA_CROSA_ORA_3505",
            "sensitivity": 0.497
        },
        {
            "convertedXnecId": "bf2c20ce-d513-48d5-a994-e712fd25d254",
            "raId": "20240430_DA_CROSA_ORA_5845",
            "sensitivity": 0.968
        },
        {
            "convertedXnecId": "70dd16e6-3745-454b-bea0-f4eb1ca9e838",
            "raId": "20240508_DA_CROSA_ORA_5622",
            "sensitivity": 0.632
        },
        {
            "convertedXnecId": "7f6d6534-2e72-4be4-8ca8-f37cd457b911",
            "raId": "20240508_DA_CROSA_ORA_5868",
            "sensitivity": 0.108
        }
    ],
    "raData": [
        {
            "costsOra": 166.65,
            "costsOraVariable": 194.09,
            "hourlyCostsAfterFixedCosts": 172.04,
            "hourlyCostsAfterReallocation": 161.65,
            "hourlyCostsFiltered": 83.4,
            "raId": "20240613_DA_CROSA_ORA_7220",
            "variableCostFinal": 174.82,
            "variableCostIntermediate": 182.84
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 166.65,
    "totalCostsAllPsts": 197.93,
    "xnecData": [
        {
            "convertedXnecId": "067d5cfdcda8c18198171d67",
            "fLimit": 36.86,
            "fPrimeB": 88.68,
            "fWithoutOrasAndPsts": 58.09
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_8.json
{
    "aggregatedVolumeDownwardCostlyAnora": 25.18,
    "aggregatedVolumeUpwardCostlyAnora": 86.71,
    "averageCostDownwardOraOrAnora": 40.58,
    "averageCostUpwardOraOrAnora": 43.07,
    "businessDay": "2024-12-27",
    "businessTimestamp": "2024-12-27T02:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "7a01827d0211c578e5933aeb",
    "csProcessVersion": 3,
    "hourCongested": true,
    "penaltyBalancingSlack": 13.49,
    "penaltyCostForAnoraVolumes": 79.27,
    "penaltyFlowSlack": 39.87,
    "psdfData": [
        {
            "convertedXnecId": "038ae5cf-487a-4900-973c-33b07943d1b2",
            "pstId": "20240402_DA_CROSA_ORA_8293",
            "sensitivity": 5958.125
        },
        {
            "convertedXnecId": "375bae2d-93fc-4bc5-ac74-1dedfd2155a1",
            "pstId": "20240405_DA_CROSA_ORA_3246",
            "sensitivity": 1783.061
        }
    ],
    "pstData": [
        {
            "costsPst": 155.43,
            "pstId": "20240402_DA_CROSA_ORA_8293",
            "tapAfter": 84.12,
            "tapBefore": 181.25
        },
        {
            "costsPst": 181.61,
            "pstId": "20240405_DA_CROSA_ORA_3246",
            "tapAfter": 61.05,
            "tapBefore": 158.55
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "45e46118-23fd-4bed-ab12-58b624c3c353",
            "raId": "20240213_DA_CROSA_ORA_9582",
            "sensitivity": 0.614
        },
        {
            "convertedXnecId": "f2650f9a-0ebe-419b-b305-e1e16611335d",
            "raId": "20240825_DA_CROSA_ORA_1030",
            "sensitivity": 0.037
        }
    ],
    "raData": [
        {
            "costsOra": 161.12,
            "costsOraVariable": 199.95,
            "hourlyCostsAfterFixedCosts": 197.11,
            "hourlyCostsAfterReallocation": 193.6,
            "hourlyCostsFiltered": 41.23,
            "raId": "20240213_DA_CROSA_ORA_9582",
            "variableCostFinal": 152.28,
            "variableCostIntermediate": 161.77
        },
        {
            "costsOra": 194.28,
            "costsOraVariable": 179.75,
            "hourlyCostsAfterFixedCosts": 160.64,
            "hourlyCostsAfterReallocation": 190.4,
            "hourlyCostsFiltered": 80.78,
            "raId": "20240825_DA_CROSA_ORA_1030",
            "variableCostFinal": 197.55,
            "variableCostIntermediate": 158.98
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 355.4,
    "totalCostsAllPsts": 337.04,
    "xnecData": [
        {
            "convertedXnecId": "038ae5cf-487a-4900-973c-33b07943d1b2",
            "fLimit": 49.95,
            "fPrimeB": 87.44,
            "fWithoutOrasAndPsts": 68.69
        },
        {
            "convertedXnecId": "375bae2d-93fc-4bc5-ac74-1dedfd2155a1",
            "fLimit": 35.51,
            "fPrimeB": 89.75,
            "fWithoutOrasAndPsts": 62.63
        },
        {
            "convertedXnecId": "45e46118-23fd-4bed-ab12-58b624c3c353",
            "fLimit": 49.93,
            "fPrimeB": 87.62,
            "fWithoutOrasAndPsts": 68.78
        },
        {
            "convertedXnecId": "f2650f9a-0ebe-419b-b305-e1e16611335d",
            "fLimit": 38.44,
            "fPrimeB": 89.79,
            "fWithoutOrasAndPsts": 64.12
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_6.json
{
    "aggregatedVolumeDownwardCostlyAnora": 88.0,
    "aggregatedVolumeUpwardCostlyAnora": 40.85,
    "averageCostDownwardOraOrAnora": 74.2,
    "averageCostUpwardOraOrAnora": 58.48,
    "businessDay": "2024-02-11",
    "businessTimestamp": "2024-02-11T01:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "d7364c43c9a5d46c32b78001",
    "csProcessVersion": 1,
    "hourCongested": false,
    "penaltyBalancingSlack": 42.47,
    "penaltyCostForAnoraVolumes": 63.37,
    "penaltyFlowSlack": 56.28,
    "psdfData": [
        {
            "convertedXnecId": "289f9862-284a-421f-bb8e-b863e40dce1b",
            "pstId": "67995c89-a42f-4ab2-b63f-124bc7e24bf5",
            "sensitivity": 6089.049
        },
        {
            "convertedXnecId": "51098980-b91c-463b-99e3-f7b5180558a9",
            "pstId": "651c12f7-c171-48ca-988d-876e23d31fd5",
            "sensitivity": 5021.476
        }
    ],
    "pstData": [
        {
            "costsPst": 153.18,
            "pstId": "67995c89-a42f-4ab2-b63f-124bc7e24bf5",
            "tapAfter": 10.63,
            "tapBefore": 196.74
        },
        {
            "costsPst": 157.04,
            "pstId": "651c12f7-c171-48ca-988d-876e23d31fd5",
            "tapAfter": 99.71,
            "tapBefore": 155.51
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "ee9763a3-4d1b-4834-81dc-7a48c92cafe9",
            "raId": "20240602_DA_CROSA_ORA_6543",
            "sensitivity": 0.519
        },
        {
            "convertedXnecId": "b0cf7b12-dde1-4297-a210-1be6f284dfda",
            "raId": "20241229_DA_CROSA_ORA_3706",
            "sensitivity": 0.897
        },
        {
            "convertedXnecId": "64a6e8ef-f8e9-4fa4-8bc9-3174dd5b57d7",
            "raId": "20240305_DA_CROSA_ORA_1472",
            "sensitivity": 0.929
        }
    ],
    "raData": [
        {
            "costsOra": 189.4,
            "costsOraVariable": 150.94,
            "hourlyCostsAfterFixedCosts": 191.66,
            "hourlyCostsAfterReallocation": 157.95,
            "hourlyCostsFiltered": 95.28,
            "raId": "20240602_DA_CROSA_ORA_6543",
            "variableCostFinal": 159.81,
            "variableCostIntermediate": 178.99
        },
        {
            "costsOra": 193.38,
            "costsOraVariable": 179.94,
            "hourlyCostsAfterFixedCosts": 156.79,
            "hourlyCostsAfterReallocation": 176.7,
            "hourlyCostsFiltered": 94.88,
            "raId": "20241229_DA_CROSA_ORA_3706",
            "variableCostFinal": 153.52,
            "variableCostIntermediate": 165.41
        },
        {
            "costsOra": 152.05,
            "costsOraVariable": 161.24,
            "hourlyCostsAfterFixedCosts": 181.43,
            "hourlyCostsAfterReallocation": 186.88,
            "hourlyCostsFiltered": 73.94,
            "raId": "20240305_DA_CROSA_ORA_1472",
            "variableCostFinal": 177.66,
            "variableCostIntermediate": 163.92
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 534.83,
    "totalCostsAllPsts": 310.22,
    "xnecData": [
        {
            "convertedXnecId": "289f9862-284a-421f-bb8e-b863e40dce1b",
            "fLimit": 40.22,
            "fPrimeB": 82.84,
            "fWithoutOrasAndPsts": 61.53
        },
        {
            "convertedXnecId": "51098980-b91c-463b-99e3-f7b5180558a9",
            "fLimit": 45.9,
            "fPrimeB": 85.09,
            "fWithoutOrasAndPsts": 65.5
        },
        {
            "convertedXnecId": "ee9763a3-4d1b-4834-81dc-7a48c92cafe9",
            "fLimit": 39.53,
            "fPrimeB": 90.94,
            "fWithoutOrasAndPsts": 65.23
        },
        {
            "convertedXnecId": "b0cf7b12-dde1-4297-a210-1be6f284dfda",
            "fLimit": 48.37,
            "fPrimeB": 81.25,
            "fWithoutOrasAndPsts": 64.81
        },
        {
            "convertedXnecId": "64a6e8ef-f8e9-4fa4-8bc9-3174dd5b57d7",
            "fLimit": 41.09,
            "fPrimeB": 87.12,
            "fWithoutOrasAndPsts": 64.11
        }
    ]
}

=== arielmbomakaeyros/como-files/MappingTSOdata_IntermediateResultsPerHour_fixed/MappingTSOdata_IntermediateResultsPerHour__file_9.json
{
    "aggregatedVolumeDownwardCostlyAnora": 19.38,
    "aggregatedVolumeUpwardCostlyAnora": 4.62,
    "averageCostDownwardOraOrAnora": 96.16,
    "averageCostUpwardOraOrAnora": 44.96,
    "businessDay": "2024-02-18",
    "businessTimestamp": "2024-02-18T02:30:00Z",
    "comoDocumentType": "CS_MAPPING_TSO_DATA_INTERMEDIATE_RESULTS_PER_HOUR",
    "comoDocumentVersion": "R24Q4V1_0",
    "crosaVersion": 1,
    "csProcessType": "6abdf8acd9ed6f6ed05d347b",
    "csProcessVersion": 1,
    "hourCongested": true,
    "penaltyBalancingSlack": 87.29,
    "penaltyCostForAnoraVolumes": 57.97,
    "penaltyFlowSlack": 5.08,
    "psdfData": [
        {
            "convertedXnecId": "86f58f49-72db-4df0-9015-3f68b1bcfd43",
            "pstId": "20240320_DA_CROSA_ORA_3333",
            "sensitivity": 1123.337
        }
    ],
    "pstData": [
        {
            "costsPst": 156.06,
            "pstId": "20240320_DA_CROSA_ORA_3333",
            "tapAfter": 92.12,
            "tapBefore": 184.95
        }
    ],
    "ptdfData": [
        {
            "convertedXnecId": "2a462a18-2421-4e39-95d1-5af374ee54bc",
            "raId": "20240420_DA_CROSA_ORA_5046",
            "sensitivity": 0.144
        },
        {
            "convertedXnecId": "bc05482f-5dfd-43f3-b535-a6a4eea9166f",
            "raId": "20240926_DA_CROSA_ORA_8735",
            "sensitivity": 0.529
        },
        {
            "convertedXnecId": "873f8841-98d9-4f61-9e74-2edf168b4aea",
            "raId": "20241219_DA_CROSA_ORA_7020",
            "sensitivity": 0.362
        },
        {
            "convertedXnecId": "f005333e-84a4-4d79-b4da-440709035999",
            "raId": "20240324_DA_CROSA_ORA_7785",
            "sensitivity": 0.411
        },
        {
            "convertedXnecId": "cb107166-1bdd-4be7-bcdb-f215431e9878",
            "raId": "20241019_DA_CROSA_ORA_3136",
            "sensitivity": 0.04
        }
    ],
    "raData": [
        {
            "costsOra": 156.34,
            "costsOraVariable": 185.08,
            "hourlyCostsAfterFixedCosts": 157.66,
            "hourlyCostsAfterReallocation": 190.6,
            "hourlyCostsFiltered": 13.3,
            "raId": "20240420_DA_CROSA_ORA_5046",
            "variableCostFinal": 186.76,
            "variableCostIntermediate": 198.8
        },
        {
            "costsOra": 169.27,
            "costsOraVariable": 189.83,
            "hourlyCostsAfterFixedCosts": 174.0,
            "hourlyCostsAfterReallocation": 176.54,
            "hourlyCostsFiltered": 87.82,
            "raId": "20240926_DA_CROSA_ORA_8735",
            "variableCostFinal": 191.62,
            "variableCostIntermediate": 184.11
        },
        {
            "costsOra": 151.69,
            "costsOraVariable": 195.97,
            "hourlyCostsAfterFixedCosts": 165.05,
            "hourlyCostsAfterReallocation": 195.89,
            "hourlyCostsFiltered": 34.83,
            "raId": "20241219_DA_CROSA_ORA_7020",
            "variableCostFinal": 190.57,
            "variableCostIntermediate": 198.29
        },
        {
            "costsOra": 198.38,
            "costsOraVariable": 177.72,
            "hourlyCostsAfterFixedCosts": 175.65,
            "hourlyCostsAfterReallocation": 179.75,
            "hourlyCostsFiltered": 73.27,
            "raId": "20240324_DA_CROSA_ORA_7785",
            "variableCostFinal": 188.63,
            "variableCostIntermediate": 167.97
        },
        {
            "costsOra": 186.33,
            "costsOraVariable": 175.81,
            "hourlyCostsAfterFixedCosts": 181.17,
            "hourlyCostsAfterReallocation": 159.74,
            "hourlyCostsFiltered": 38.55,
            "raId": "20241019_DA_CROSA_ORA_3136",
            "variableCostFinal": 176.42,
            "variableCostIntermediate": 163.77
        }
    ],
    "timeHorizon": "dayAhead",
    "totalCostsAllOras": 862.01,
    "totalCostsAllPsts": 156.06,
    "xnecData": [
        {
            "convertedXnecId": "86f58f49-72db-4df0-9015-3f68b1bcfd43",
            "fLimit": 38.86,
            "fPrimeB": 93.92,
            "fWithoutOrasAndPsts": 66.39
        },
        {
            "convertedXnecId": "2a462a18-2421-4e39-95d1-5af374ee54bc",
            "fLimit": 35.68,
            "fPrimeB": 87.52,
            "fWithoutOrasAndPsts": 61.6
        },
        {
            "convertedXnecId": "bc05482f-5dfd-43f3-b535-a6a4eea9166f",
            "fLimit": 31.71,
            "fPrimeB": 89.78,
            "fWithoutOrasAndPsts": 60.75
        },
        {
            "convertedXnecId": "873f8841-98d9-4f61-9e74-2edf168b4aea",
            "fLimit": 36.4,
            "fPrimeB": 89.52,
            "fWithoutOrasAndPsts": 62.96
        },
        {
            "convertedXnecId": "f005333e-84a4-4d79-b4da-440709035999",
            "fLimit": 48.22,
            "fPrimeB": 83.52,
            "fWithoutOrasAndPsts": 65.87
        },
        {
            "convertedXnecId": "cb107166-1bdd-4be7-bcdb-f215431e9878",
            "fLimit": 41.04,
            "fPrimeB": 80.07,
            "fWithoutOrasAndPsts": 60.55
        }
    ]
}
