=== arielmbomakaeyros/como-files/old/MappingDetailedResults_Schema_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/MappingDetailedResults_Schema",
    "title": "MappingDetailedResult",
    "type": "object",
    "description": "The detailed result from CS mapping",
    "properties": {
        "businessDay": {
            "description": "Business date - a date for which the process is executed",
            "type": "string"
        },
        "crosaVersion": {
            "description": "Version of the related CROSA process",
            "type": "integer"
        },
        "csProcessVersion": {
            "description": "Version of the related Cost Sharing process",
            "type": "integer"
        },
        "dataPerHour": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/DataPerHourOfTheCrosa"
            }
        },
        "dataPerXnec": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/DataPerXnec"
            }
        },
        "dataPerXnecAndXra": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/DataPerXnecAndXra"
            }
        },
        "dataPerXra": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/DataPerXra"
            }
        },
        "timeHorizon": {
            "description": "Time horizon for which the Cost Sharing/CROSA process is executed",
            "type": "string"
        }
    },
    "definitions": {
        "DataPerHourOfTheCrosa": {
            "type": "object",
            "properties": {
                "aggregatedVolumeDownwardCostlyAnora": {
                    "type": "number"
                },
                "aggregatedVolumeUpwardCostlyAnora": {
                    "type": "number"
                },
                "averageCostDownwardOraOrAnora": {
                    "type": "number"
                },
                "averageCostUpwardOraOrAnora": {
                    "type": "number"
                },
                "penaltyCostForAnoraVolumes": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "totalCostsAllOras": {
                    "type": "number"
                },
                "totalIndividualShare": {
                    "type": "number"
                },
                "totalRelativeWeightsAfterRba": {
                    "type": "number"
                },
                "totalRelativeWeightsBeforeRba": {
                    "type": "number"
                }
            },
            "additionalProperties": false,
            "required": [
                "timestamp"
            ]
        },
        "DataPerXnec": {
            "type": "object",
            "properties": {
                "deltaMinus": {
                    "type": "number"
                },
                "deltaPlus": {
                    "type": "number"
                },
                "fAfterRao": {
                    "type": "number"
                },
                "fLimit": {
                    "type": "number"
                },
                "fMax": {
                    "type": "number"
                },
                "leastCostWeightRi": {
                    "type": "number"
                },
                "lowerBalancingDualValue": {
                    "type": "number"
                },
                "lowerBalancingSlack": {
                    "type": "number"
                },
                "powerFlowDualValue": {
                    "type": "number"
                },
                "powerFlowSlack": {
                    "type": "number"
                },
                "relativeCostWeightAfterRba": {
                    "type": "number"
                },
                "relativeCostWeightBeforeRba": {
                    "type": "number"
                },
                "selectedXnecResultId": {
                    "type": "string"
                },
                "shareOfTotalCosts": {
                    "type": "number"
                },
                "sumDeltaMinus": {
                    "type": "number"
                },
                "sumDeltaPlus": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "totalAdjustedFlow": {
                    "type": "number"
                },
                "upperBalancingDualValue": {
                    "type": "number"
                },
                "upperBalancingSlack": {
                    "type": "number"
                },
                "xnecId": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "selectedXnecResultId",
                "timestamp",
                "xnecId"
            ]
        },
        "DataPerXnecAndXra": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "valueType": {
                    "$ref": "#/definitions/ValueType"
                },
                "xnecId": {
                    "type": "string"
                },
                "xraId": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "timestamp",
                "valueType",
                "xnecId",
                "xraId"
            ]
        },
        "DataPerXra": {
            "type": "object",
            "properties": {
                "orderedVolume": {
                    "type": "number"
                },
                "sumAlphaOrBetaOverXnecs": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "totalCost": {
                    "type": "number"
                },
                "xraId": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "sumAlphaOrBetaOverXnecs",
                "timestamp",
                "xraId"
            ]
        },
        "ValueType": {
            "type": "string",
            "enum": [
                "optimizationVariable",
                "sensitivity"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "businessDay",
        "crosaVersion",
        "csProcessVersion",
        "timeHorizon"
    ]
}

=== arielmbomakaeyros/como-files/MappingDetailedResults_test_data/MappingDetailedResults_file_6.json
{
    "businessDay": "2024-04-08",
    "crosaVersion": 1,
    "csProcessVersion": 5,
    "dataPerHour": [
        {
            "aggregatedVolumeDownwardCostlyAnora": 22.75,
            "aggregatedVolumeUpwardCostlyAnora": 1.58,
            "averageCostDownwardOraOrAnora": 17.01,
            "averageCostUpwardOraOrAnora": 39.79,
            "penaltyCostForAnoraVolumes": 74.71,
            "timestamp": "2024-10-10T02:30:00Z",
            "totalCostsAllOras": 12.16,
            "totalIndividualShare": 32.19,
            "totalRelativeWeightsAfterRba": 69.98,
            "totalRelativeWeightsBeforeRba": 33.52
        }
    ],
    "dataPerXnec": [
        {
            "deltaMinus": 48.4,
            "deltaPlus": 86.12,
            "fAfterRao": 15.99,
            "fLimit": 80.21,
            "fMax": 59.24,
            "leastCostWeightRi": 86.14,
            "lowerBalancingDualValue": 14.16,
            "lowerBalancingSlack": 78.01,
            "powerFlowDualValue": 74.72,
            "powerFlowSlack": 67.35,
            "relativeCostWeightAfterRba": 21.1,
            "relativeCostWeightBeforeRba": 10.99,
            "selectedXnecResultId": "296f7b14570679d1d340e8ed",
            "shareOfTotalCosts": 51.23,
            "sumDeltaMinus": 23.13,
            "sumDeltaPlus": 65.74,
            "timestamp": "2023-12-24T02:30:00Z",
            "totalAdjustedFlow": 66.34,
            "upperBalancingDualValue": 14.61,
            "upperBalancingSlack": 74.89,
            "xnecId": "d68e33935554b9fb50fc470b"
        }
    ],
    "dataPerXnecAndXra": [
        {
            "timestamp": "2024-07-31T02:30:00Z",
            "value": 30.93,
            "valueType": "sensitivity",
            "xnecId": "1487a24c7aec6a2aff92c640",
            "xraId": "269d5817c1321208efe35ee6"
        }
    ],
    "dataPerXra": [
        {
            "orderedVolume": 1.46,
            "sumAlphaOrBetaOverXnecs": 98.82,
            "timestamp": "2024-03-03T01:30:00Z",
            "totalCost": 27.36,
            "xraId": "a3bb6405f13c38a790c0ce7e"
        }
    ],
    "timeHorizon": "dayAhead"
}
