=== arielmbomakaeyros/como-files/flat_list/schema/CO_Flat_List_Schema_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/CO_Flat_List_Schema",
    "title": "ContingencyFlatList",
    "type": "object",
    "properties": {
        "businessTimestamp": {
            "type": [
                "string",
                "null"
            ]
        },
        "cdsId": {
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "contingencyGroupList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/ContingencyGroup"
            }
        },
        "contingencyList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/Contingency"
            }
        },
        "contingencyListId": {
            "type": "string"
        },
        "documentId": {
            "type": "string"
        },
        "gridModelId": {
            "type": "string"
        },
        "ownerCode": {
            "type": "string"
        },
        "ownerRole": {
            "type": "string"
        },
        "timeHorizon": {
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "timeInterval": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "#/definitions/TimeInterval"
                }
            ]
        },
        "version": {
            "type": "integer"
        }
    },
    "definitions": {
        "Contingency": {
            "type": "object",
            "properties": {
                "contingencyCondition": {
                    "description": "Only present if contingencyType is ExceptionalContingency.",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ContingencyConditionKind"
                        }
                    ]
                },
                "contingencyType": {
                    "$ref": "#/definitions/ContingencyTypeKind"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentOperatorCode": {
                    "description": "mRID of a SystemOperator object.\n\nSystem operator that is operating the equipment that is being run a contingency on.",
                    "type": "string"
                },
                "groupCode": {
                    "type": "string"
                },
                "mrid": {
                    "type": "string"
                },
                "mustStudy": {
                    "description": "CIM desc : Specifies the requirement of study the contingency under normal operating conditions. True means the contingency must be study in a normal scenario. False means that the contingency does not need to be included in the scenario. This is the default value if mustStudy is missing.",
                    "type": "boolean"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "probability": {
                    "description": "The allowed value range is [0,100].\nCIM desc : Normal probability of the occurrence of the contingency based on normal operational condition. The value is used as the default if the probability is missing.",
                    "type": [
                        "number",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "contingencyType",
                "equipmentOperatorCode",
                "groupCode",
                "mrid",
                "mustStudy"
            ]
        },
        "ContingencyConditionKind": {
            "type": "string",
            "enum": [
                "design",
                "environmental",
                "geographicalLocation",
                "malfunction",
                "operation"
            ]
        },
        "ContingencyGroup": {
            "type": "object",
            "properties": {
                "equipmentList": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "$ref": "#/definitions/Equipment"
                    }
                },
                "groupCode": {
                    "type": "string"
                }
            },
            "additionalProperties": true,
            "required": [
                "groupCode"
            ]
        },
        "ContingencyTypeKind": {
            "type": "string",
            "enum": [
                "exceptional",
                "ordinary",
                "outOfRange"
            ]
        },
        "DocumentTypeKind": {
            "type": "string",
            "const": "INTERNAL_CO_FLAT_LIST"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "Equipment": {
            "type": "object",
            "properties": {
                "areaCode": {
                    "type": "string"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentMrid": {
                    "type": "string"
                },
                "equipmentType": {
                    "$ref": "#/definitions/EquipmentType"
                },
                "mrid": {
                    "type": "string"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "areaCode",
                "equipmentMrid",
                "equipmentType",
                "mrid"
            ]
        },
        "EquipmentType": {
            "type": "string",
            "enum": [
                "bus",
                "busbar",
                "gen",
                "line",
                "load",
                "shuntCompensator",
                "staticVarCompensator",
                "switch",
                "transformer"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "TimeInterval": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "format": "date-time"
                },
                "to": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "required": [
                "from",
                "to"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "cdsId",
        "comoDocumentType",
        "comoDocumentVersion",
        "contingencyListId",
        "documentId",
        "gridModelId",
        "ownerCode",
        "ownerRole",
        "timeHorizon",
        "version"
    ]
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_5.json
{
    "businessTimestamp": "2024-01-05T15:29:14",
    "cdsId": "fe414335-08cf-4c63-a676-52de0333e6aa",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "7ca1ec83-022f-49cd-870b-964d68205fdc",
                    "equipmentType": "gen",
                    "mrid": "ab234d76-1839-4f46-a116-ddf931a15ce3",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "7e417ea0-d840-4fd1-99fa-2918b05d8481",
                    "equipmentType": "staticVarCompensator",
                    "mrid": "08ea6de5-99fa-453f-8ca2-ee2f7a0a04f3",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "629aa5c6-ab30-463b-9935-70843b3a3aa0",
                    "equipmentType": "shuntCompensator",
                    "mrid": "96fe0637-0334-450d-ab42-f108dd5f82ad",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "dc46fe8c-0d5b-41e8-894b-e73aece5b9e3"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "174a03e9-7ac3-479f-990d-80885047454d",
                    "equipmentType": "bus",
                    "mrid": "7e199059-f293-4b11-9bcf-61454cf7a076",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "1d8c8107-3e9d-47c7-b38d-bff530f7a536"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "3d03f2e2-e465-4dae-bd7b-6458b772e968",
                    "equipmentType": "gen",
                    "mrid": "89f9941f-59f4-4b2b-bd89-ac6e6fb001d4",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "66cd2766-99e5-4155-b5c8-d80ea3976b02",
                    "equipmentType": "load",
                    "mrid": "379ea2a4-00e6-47c6-8265-4bfbf8581820",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "d123dd78-867c-4166-9059-c11e89bb44e6",
                    "equipmentType": "line",
                    "mrid": "c8c4a187-1092-469b-bb1a-ed84aeb13176",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "31dc91c2-446d-4414-89e3-4941798e9f7a"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": null,
            "contingencyType": "outOfRange",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "9d30c04d-0255-4002-b741-1d029f6940d7",
            "groupCode": "7a48fe6f-68b1-4d3e-a787-1a90bb8e36e2",
            "mrid": "7faf8c6c-92dc-4963-846c-20eac10d4f1a",
            "mustStudy": false,
            "name": "Contingency 1",
            "probability": null
        },
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "ordinary",
            "description": null,
            "equipmentOperatorCode": "a41f6604-8e31-4523-a167-610ce8b3a66e",
            "groupCode": "0ce65bb2-58ab-42b3-a64c-a1e58b0a3536",
            "mrid": "6776f831-fa06-457b-a25e-34d615913592",
            "mustStudy": true,
            "name": null,
            "probability": null
        },
        {
            "contingencyCondition": null,
            "contingencyType": "outOfRange",
            "description": null,
            "equipmentOperatorCode": "b25aebdc-1e26-498c-a39c-786f4c46d3d2",
            "groupCode": "3d2d26cf-d322-4f0d-be7f-185b369acd3a",
            "mrid": "b7326f4d-7c24-43fe-8906-e02350c8c5b2",
            "mustStudy": false,
            "name": null,
            "probability": null
        }
    ],
    "contingencyListId": "7515f38f-ebbc-414a-894d-9fa3df2df653",
    "documentId": "4c1d3d7e-6c7e-4a10-a6f3-9a391733ba2b",
    "gridModelId": "250ff2d6-d49c-42da-b725-3ce6276946bc",
    "ownerCode": "10XSK-SEPS-GRIDB",
    "ownerRole": "System Operator",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-05T00:00:00",
        "to": "2024-01-05T19:00:00"
    },
    "version": 7
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_1.json
{
    "businessTimestamp": "2024-01-01T03:00:10",
    "cdsId": "26e79ec1-912d-4598-b1c7-3547d3d64d16",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YSI-ELES-----O",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "193ccad0-3719-49fb-bb1e-f97440c6d467",
                    "equipmentType": "load",
                    "mrid": "1d754e5b-8089-4d84-8288-b4590f01b0df",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "4912516d-8d76-4228-80f8-30675b18296a"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YSI-ELES-----O",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "8bb1b7d2-3883-4107-b51f-6461de1b7ab2",
                    "equipmentType": "switch",
                    "mrid": "9c3d44a8-b6f5-4200-b9de-046937e8092d",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YSI-ELES-----O",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "a8a5d68b-94d2-4931-b14c-e284137adb23",
                    "equipmentType": "gen",
                    "mrid": "d788815b-fcd9-4ff0-bfd4-bb977deae4c7",
                    "name": "Equipment 2"
                }
            ],
            "groupCode": "836ecd4a-01c1-45bb-ada8-08957fce88e4"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "malfunction",
            "contingencyType": "ordinary",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "950a7ea5-d3da-449c-aaee-e3fe4f6d4a51",
            "groupCode": "7001d218-b820-48c8-9b3a-9c38f4fc7998",
            "mrid": "e5eade97-32ef-4053-b52b-bfdcb0c63ade",
            "mustStudy": false,
            "name": "Contingency 1",
            "probability": null
        },
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "exceptional",
            "description": "Sample contingency description 2",
            "equipmentOperatorCode": "b0e31bc7-cae0-434a-861f-2c2c1954958a",
            "groupCode": "90fef6d6-c2b9-42ed-abbd-b6cd556cfb64",
            "mrid": "2b3e5849-a1d3-4eb5-b0ff-c09eafadbe4b",
            "mustStudy": false,
            "name": "Contingency 2",
            "probability": 76.06
        }
    ],
    "contingencyListId": "25b60101-c881-4dfb-9e8e-251d737c7f72",
    "documentId": "40f98fca-e7d8-4fbb-baff-97bfde3570e4",
    "gridModelId": "5f675029-fed4-4a12-a54e-5c24d8f3c2d7",
    "ownerCode": "10XSI-ELES-----1",
    "ownerRole": "Network Engineer",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-01T00:00:00",
        "to": "2024-01-01T07:00:00"
    },
    "version": 4
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_6.json
{
    "businessTimestamp": "2024-01-06T01:23:41",
    "cdsId": "31fa71ff-d070-4b5d-b0c5-4640f23ed8a2",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "17e268b4-764c-422c-90cc-8cf042accb29",
                    "equipmentType": "switch",
                    "mrid": "773e40fa-81a0-4280-9e12-515a7af97e62",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "a852ed06-8978-470e-92c2-8b189109c716",
                    "equipmentType": "gen",
                    "mrid": "cdb69f00-b305-4f37-903c-94b8cccf3840",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "b6960773-5ef8-4ca3-907e-914481ef2dd3",
                    "equipmentType": "bus",
                    "mrid": "0c54ee53-3294-4b65-872f-e2773eebd734",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "5bb251d7-325d-4baf-89ee-ea2550cbc95f"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "dbc8b7dd-5396-4a81-aeb8-644437eee1b1",
                    "equipmentType": "transformer",
                    "mrid": "8ca636fd-995f-4969-b5ee-1ab374cd46ae",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "10297fe2-0371-49d4-9956-011f8709dd33",
                    "equipmentType": "busbar",
                    "mrid": "d6fffc13-73e7-471f-a4de-523566d6d300",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "985a185a-fdb5-4c49-a556-8ad09f662e24",
                    "equipmentType": "staticVarCompensator",
                    "mrid": "0e7a3f37-d670-4252-8059-2ae4da0dcdeb",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "3d1e579f-771a-4b23-8a16-45f6ae2dc153"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "9b9a3d3f-def5-42ae-88e5-36299094a356",
                    "equipmentType": "load",
                    "mrid": "b693b73e-67dd-460b-9319-6a70664ff57e",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "7e6a46a2-aee0-4d88-aa6a-09032d7accef",
                    "equipmentType": "staticVarCompensator",
                    "mrid": "bf64b0cf-2840-4cf2-a5f6-459a09c0efbc",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "c858e67d-5db5-4845-a3d5-d1da19b23558",
                    "equipmentType": "switch",
                    "mrid": "71a602e4-8bb1-4518-998c-621b34f8dca8",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "54a03f70-3a6a-4546-8d98-8b992f4095b6"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": null,
            "contingencyType": "ordinary",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "257207ec-c9d7-46fb-9e72-a23574ad9f14",
            "groupCode": "2aae5301-8171-4f58-bb8e-e21835c86f56",
            "mrid": "986f8259-c2ac-44d9-8298-24d4f12254c9",
            "mustStudy": false,
            "name": "Contingency 1",
            "probability": 21.49
        },
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "outOfRange",
            "description": "Sample contingency description 2",
            "equipmentOperatorCode": "4afdceaf-3744-486c-8913-9aac915336a3",
            "groupCode": "702670dc-4955-4277-8a39-69642fdf8f79",
            "mrid": "7f18b558-4c41-42a8-9111-c7582136dfde",
            "mustStudy": true,
            "name": "Contingency 2",
            "probability": 72.6
        },
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "exceptional",
            "description": null,
            "equipmentOperatorCode": "2782191c-b691-4ec5-92ca-4c8e279fe96f",
            "groupCode": "81e79470-a2f7-48fa-b2b6-9953efd3221a",
            "mrid": "54248114-a436-4cf7-870e-3c31bbda95c9",
            "mustStudy": true,
            "name": "Contingency 3",
            "probability": null
        }
    ],
    "contingencyListId": "6bbb0fbf-8714-451f-bd8f-286911b9ca7a",
    "documentId": "f1bce2b8-0829-441e-bacf-2840629cd2f5",
    "gridModelId": "1437bde2-1eb7-4a29-9b8a-ccdb523abd4c",
    "ownerCode": "10X1001A1001A329",
    "ownerRole": "System Operator",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-06T00:00:00",
        "to": "2024-01-06T09:00:00"
    },
    "version": 5
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/aeco_co_flatlist/CO_Flat_List_Schema_fixed_4.json
{
    "businessTimestamp": "2025-01-04T00:30:00",
    "cdsId": "342f768b-aa3f-41fb-b6ac-572d2ca0cc1a",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YSK-SEPS-----K",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "35a2d041-91bd-45a3-97af-9143a03a6fbd",
                    "equipmentType": "busbar",
                    "mrid": "d93ca076-40db-487f-be83-7f51d738fee8",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "943ed709-50a8-42a2-aa0e-3357e5a4f696"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "environmental",
            "contingencyType": "exceptional",
            "description": null,
            "equipmentOperatorCode": "7b8e5707-af63-4c80-b852-2e5cf434ed51",
            "groupCode": "943ed709-50a8-42a2-aa0e-3357e5a4f696",
            "mrid": "d7c3cb7d-36d3-4ccc-996f-7c8088677e3c",
            "mustStudy": true,
            "name": null,
            "probability": null
        }
    ],
    "contingencyListId": "1382c0d6-0af6-4b77-9321-66eecb98ddc9",
    "documentId": "29154ba6-8b39-4567-987a-7471972e8356",
    "gridModelId": "d41318a3-c956-4e00-a767-ff9aa5ca9de4",
    "ownerCode": "10XSK-SEPS-GRIDB",
    "ownerRole": "Grid Manager",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-04T00:00:00",
        "to": "2025-01-04T01:00:00"
    },
    "version": 2
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_Flat_List_Schema_fixed_6.json
{
    "businessTimestamp": "2025-01-06T00:30:00",
    "cdsId": "52311e1f-d912-4fd3-ada6-069b46a17ef9",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "48596adb-1933-4980-b6db-1cc2122669ae",
                    "equipmentType": "transformer",
                    "mrid": "aa79f671-9b94-43cf-bc7e-26a068ee9fa1",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YHU-MAVIR----U",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "cff20ac0-c43e-415a-a90c-16bf18339753",
                    "equipmentType": "gen",
                    "mrid": "20c7c740-6574-48ac-a9b0-abcd04822d6a",
                    "name": "Equipment 2"
                }
            ],
            "groupCode": "c85330c8-73a9-40a3-80d1-7415bd917896"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": null,
            "contingencyType": "outOfRange",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "7576bf0a-0b04-4b77-94b8-adbe7c27872d",
            "groupCode": "c85330c8-73a9-40a3-80d1-7415bd917896",
            "mrid": "39499df7-04ca-4e92-8cd0-6871887451d6",
            "mustStudy": true,
            "name": "Contingency 1",
            "probability": null
        }
    ],
    "contingencyListId": "b7072662-a923-49ae-b1c6-2b0079c25a9f",
    "documentId": "eaf45356-c50e-4d49-af95-a4341debbccb",
    "gridModelId": "cb077d25-0ec0-4a96-a2a3-2b17b2b6ff36",
    "ownerCode": "10X1001A1001A329",
    "ownerRole": "Network Engineer",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-06T00:00:00",
        "to": "2025-01-06T01:00:00"
    },
    "version": 3
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/aeco_co_flatlist_2025_02_26_b/CO_Flat_List_Schema_fixed_5.json
{
    "businessTimestamp": "2025-01-05T00:30:00",
    "cdsId": "58863cc3-b840-43fd-879e-2b111043c8c1",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YAT-APG------L",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "b98ca700-1268-40fc-ab2c-85b80f8a8126",
                    "equipmentType": "shuntCompensator",
                    "mrid": "6901f1b5-6a2d-486d-9c30-c34261f4d2ed",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YAT-APG------L",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "9297ec8f-3d3c-4f50-a80c-5c1f7db84aee",
                    "equipmentType": "staticVarCompensator",
                    "mrid": "b054dc22-8e00-4b56-a43e-9471a6b3c3f7",
                    "name": "Equipment 2"
                }
            ],
            "groupCode": "e6c3bf19-2ff4-4d41-9c90-df3c65644fa9"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YAT-APG------L",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "43782726-4796-4271-80da-674125f39ee4",
                    "equipmentType": "gen",
                    "mrid": "fe0e158c-799a-43dd-8d48-5b13e589e550",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "e4ae9d27-4419-4c21-adb9-e568bd25358a"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": null,
            "contingencyType": "ordinary",
            "description": null,
            "equipmentOperatorCode": "00eb332e-e370-4e81-aae6-a3e4bbdf82c8",
            "groupCode": "e6c3bf19-2ff4-4d41-9c90-df3c65644fa9",
            "mrid": "7c1099ea-6ee6-4242-b1e2-070c5d8dee1c",
            "mustStudy": true,
            "name": "Contingency 1",
            "probability": null
        },
        {
            "contingencyCondition": null,
            "contingencyType": "outOfRange",
            "description": null,
            "equipmentOperatorCode": "d7bb62b3-365c-4a5e-874c-0f539b5a2ed4",
            "groupCode": "e4ae9d27-4419-4c21-adb9-e568bd25358a",
            "mrid": "bcf7fbc7-b7d2-449e-ad09-26f3bf7de310",
            "mustStudy": false,
            "name": null,
            "probability": null
        }
    ],
    "contingencyListId": "f9afbe07-769b-4d5c-8310-c59fde9605f4",
    "documentId": "6d65cc44-67b6-4ba7-9645-3b53b2666bd5",
    "gridModelId": "1760e4a0-0d00-4d94-858e-cc8a9cc33cbd",
    "ownerCode": "10XAT-APG------Z",
    "ownerRole": "Network Engineer",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-05T00:00:00",
        "to": "2025-01-05T01:00:00"
    },
    "version": 3
}
