=== arielmbomakaeyros/como-files/flat_list/schema/CO_Flat_List_Schema_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/CO_Flat_List_Schema",
    "title": "ContingencyFlatList",
    "type": "object",
    "properties": {
        "businessTimestamp": {
            "type": [
                "string",
                "null"
            ]
        },
        "cdsId": {
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "contingencyGroupList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/ContingencyGroup"
            }
        },
        "contingencyList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/Contingency"
            }
        },
        "contingencyListId": {
            "type": "string"
        },
        "documentId": {
            "type": "string"
        },
        "gridModelId": {
            "type": "string"
        },
        "ownerCode": {
            "type": "string"
        },
        "ownerRole": {
            "type": "string"
        },
        "timeHorizon": {
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "timeInterval": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "#/definitions/TimeInterval"
                }
            ]
        },
        "version": {
            "type": "integer"
        }
    },
    "definitions": {
        "Contingency": {
            "type": "object",
            "properties": {
                "contingencyCondition": {
                    "description": "Only present if contingencyType is ExceptionalContingency.",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ContingencyConditionKind"
                        }
                    ]
                },
                "contingencyType": {
                    "$ref": "#/definitions/ContingencyTypeKind"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentOperatorCode": {
                    "description": "mRID of a SystemOperator object.\n\nSystem operator that is operating the equipment that is being run a contingency on.",
                    "type": "string"
                },
                "groupCode": {
                    "type": "string"
                },
                "mrid": {
                    "type": "string"
                },
                "mustStudy": {
                    "description": "CIM desc : Specifies the requirement of study the contingency under normal operating conditions. True means the contingency must be study in a normal scenario. False means that the contingency does not need to be included in the scenario. This is the default value if mustStudy is missing.",
                    "type": "boolean"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "probability": {
                    "description": "The allowed value range is [0,100].\nCIM desc : Normal probability of the occurrence of the contingency based on normal operational condition. The value is used as the default if the probability is missing.",
                    "type": [
                        "number",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "contingencyType",
                "equipmentOperatorCode",
                "groupCode",
                "mrid",
                "mustStudy"
            ]
        },
        "ContingencyConditionKind": {
            "type": "string",
            "enum": [
                "design",
                "environmental",
                "geographicalLocation",
                "malfunction",
                "operation"
            ]
        },
        "ContingencyGroup": {
            "type": "object",
            "properties": {
                "equipmentList": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "$ref": "#/definitions/Equipment"
                    }
                },
                "groupCode": {
                    "type": "string"
                }
            },
            "additionalProperties": true,
            "required": [
                "groupCode"
            ]
        },
        "ContingencyTypeKind": {
            "type": "string",
            "enum": [
                "exceptional",
                "ordinary",
                "outOfRange"
            ]
        },
        "DocumentTypeKind": {
            "type": "string",
            "const": "INTERNAL_CO_FLAT_LIST"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "Equipment": {
            "type": "object",
            "properties": {
                "areaCode": {
                    "type": "string"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentMrid": {
                    "type": "string"
                },
                "equipmentType": {
                    "$ref": "#/definitions/EquipmentType"
                },
                "mrid": {
                    "type": "string"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "areaCode",
                "equipmentMrid",
                "equipmentType",
                "mrid"
            ]
        },
        "EquipmentType": {
            "type": "string",
            "enum": [
                "bus",
                "busbar",
                "gen",
                "line",
                "load",
                "shuntCompensator",
                "staticVarCompensator",
                "switch",
                "transformer"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "TimeInterval": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "format": "date-time"
                },
                "to": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "required": [
                "from",
                "to"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "cdsId",
        "comoDocumentType",
        "comoDocumentVersion",
        "contingencyListId",
        "documentId",
        "gridModelId",
        "ownerCode",
        "ownerRole",
        "timeHorizon",
        "version"
    ]
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_Flat_List_Schema_fixed_1.json
{
    "businessTimestamp": "2025-01-01T00:30:00",
    "cdsId": "21727fde-d542-421b-9189-dfd61c53067a",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YSI-ELES-----O",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "64d4d682-e6ed-4c1a-9d45-b4b5b25ea3c2",
                    "equipmentType": "gen",
                    "mrid": "01e12979-e478-4b0c-ad7a-da13a27e8c5a",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YSI-ELES-----O",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "7bcd95c6-518f-474f-8af4-4a5d453a2b9b",
                    "equipmentType": "transformer",
                    "mrid": "fb3c710d-aa5e-4fc8-80fc-cc50400d5f5c",
                    "name": "Equipment 2"
                }
            ],
            "groupCode": "b80184bf-f508-45e3-826b-22a14f6b2da2"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "malfunction",
            "contingencyType": "exceptional",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "9d2d417c-c13e-4405-b3fb-40f722a74bdc",
            "groupCode": "b80184bf-f508-45e3-826b-22a14f6b2da2",
            "mrid": "371b4929-e389-4766-8380-05193cb946df",
            "mustStudy": false,
            "name": null,
            "probability": 51.87
        }
    ],
    "contingencyListId": "53cfe06e-ca3e-4eca-a56b-379882c83e69",
    "documentId": "7e204922-3d34-4d5e-9578-06754eb81d69",
    "gridModelId": "f2fcf01c-3a93-46cb-9bcc-cca5c8d70b63",
    "ownerCode": "10XSI-ELES-----1",
    "ownerRole": "Network Engineer",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-01T00:00:00",
        "to": "2025-01-01T01:00:00"
    },
    "version": 10
}

=== arielmbomakaeyros/como-files/ae_co_flatlist/Example CS concept test.json
{
    "businessTimestamp": "2031-10-19T01:30:00Z",
    "documentId": "66a2614fac244b410091070d",
    "ownerCode": "22XCORESO------S",
    "ownerRole": "rcc",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2031-10-19T01:00:00Z",
        "to": "2031-10-19T02:00:00Z"
    },
    "version": 1,
    "cdsId": "bsab06817a2dc1bbaab06817a2dc1b",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "gridModelId": "aaab06817a2dc1bbaab06817a2dc1aa",
    "contingencyListId": "19c448e3a7834f29a611b6a2aa32e240",
    "contingencyList": [
        {
            "mrid": "co_mrid_1",
            "groupCode": "23dd4c7f-cf4f-4047-8eb9-4a80f1681413", 
            "contingencyType": "exceptional",
            "equipmentOperatorCode": "10XRO-TEL------2",
            "mustStudy": true
        }
    ],
    "contingencyGroupList": [
        {
            "groupCode": "23dd4c7f-cf4f-4047-8eb9-4a80f1681413",
            "equipmentList": [
                {
                    "description": null,
                    "mrid": "acdf973f-66a7-41c3-b180-77191d0db7ed",
                    "name": "Line 1-7 Loss",
                    "equipmentMrid": "_7c1c97f1-177c-4a14-a6ff-2ea1b2e67b1f",
                    "equipmentType": "line", 
                    "areaCode": "10YRO-TEL------P"
                }
            ]
        }
    ]
}
