=== arielmbomakaeyros/como-files/flat_list/schema/CO_Flat_List_Schema_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/CO_Flat_List_Schema",
    "title": "ContingencyFlatList",
    "type": "object",
    "properties": {
        "businessTimestamp": {
            "type": [
                "string",
                "null"
            ]
        },
        "cdsId": {
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "contingencyGroupList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/ContingencyGroup"
            }
        },
        "contingencyList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/Contingency"
            }
        },
        "contingencyListId": {
            "type": "string"
        },
        "documentId": {
            "type": "string"
        },
        "gridModelId": {
            "type": "string"
        },
        "ownerCode": {
            "type": "string"
        },
        "ownerRole": {
            "type": "string"
        },
        "timeHorizon": {
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "timeInterval": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "#/definitions/TimeInterval"
                }
            ]
        },
        "version": {
            "type": "integer"
        }
    },
    "definitions": {
        "Contingency": {
            "type": "object",
            "properties": {
                "contingencyCondition": {
                    "description": "Only present if contingencyType is ExceptionalContingency.",
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ContingencyConditionKind"
                        }
                    ]
                },
                "contingencyType": {
                    "$ref": "#/definitions/ContingencyTypeKind"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentOperatorCode": {
                    "description": "mRID of a SystemOperator object.\n\nSystem operator that is operating the equipment that is being run a contingency on.",
                    "type": "string"
                },
                "groupCode": {
                    "type": "string"
                },
                "mrid": {
                    "type": "string"
                },
                "mustStudy": {
                    "description": "CIM desc : Specifies the requirement of study the contingency under normal operating conditions. True means the contingency must be study in a normal scenario. False means that the contingency does not need to be included in the scenario. This is the default value if mustStudy is missing.",
                    "type": "boolean"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "probability": {
                    "description": "The allowed value range is [0,100].\nCIM desc : Normal probability of the occurrence of the contingency based on normal operational condition. The value is used as the default if the probability is missing.",
                    "type": [
                        "number",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "contingencyType",
                "equipmentOperatorCode",
                "groupCode",
                "mrid",
                "mustStudy"
            ]
        },
        "ContingencyConditionKind": {
            "type": "string",
            "enum": [
                "design",
                "environmental",
                "geographicalLocation",
                "malfunction",
                "operation"
            ]
        },
        "ContingencyGroup": {
            "type": "object",
            "properties": {
                "equipmentList": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "$ref": "#/definitions/Equipment"
                    }
                },
                "groupCode": {
                    "type": "string"
                }
            },
            "additionalProperties": true,
            "required": [
                "groupCode"
            ]
        },
        "ContingencyTypeKind": {
            "type": "string",
            "enum": [
                "exceptional",
                "ordinary",
                "outOfRange"
            ]
        },
        "DocumentTypeKind": {
            "type": "string",
            "const": "INTERNAL_CO_FLAT_LIST"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "Equipment": {
            "type": "object",
            "properties": {
                "areaCode": {
                    "type": "string"
                },
                "description": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "equipmentMrid": {
                    "type": "string"
                },
                "equipmentType": {
                    "$ref": "#/definitions/EquipmentType"
                },
                "mrid": {
                    "type": "string"
                },
                "name": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "additionalProperties": true,
            "required": [
                "areaCode",
                "equipmentMrid",
                "equipmentType",
                "mrid"
            ]
        },
        "EquipmentType": {
            "type": "string",
            "enum": [
                "bus",
                "busbar",
                "gen",
                "line",
                "load",
                "shuntCompensator",
                "staticVarCompensator",
                "switch",
                "transformer"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "TimeInterval": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "format": "date-time"
                },
                "to": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "required": [
                "from",
                "to"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "cdsId",
        "comoDocumentType",
        "comoDocumentVersion",
        "contingencyListId",
        "documentId",
        "gridModelId",
        "ownerCode",
        "ownerRole",
        "timeHorizon",
        "version"
    ]
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/aeco_co_flatlist/CO_Flat_List_Schema_fixed_2.json
{
    "businessTimestamp": "2025-01-02T00:30:00",
    "cdsId": "9717c2d8-1616-49e2-a312-e613d5c7a5aa",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "7208059b-88f4-4f12-91ed-b2f7e5c93824",
                    "equipmentType": "shuntCompensator",
                    "mrid": "db5d3d7a-3e7a-4873-a048-81800da78c3f",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "669d336d-6470-4ae5-93cc-1fbe81767448",
                    "equipmentType": "transformer",
                    "mrid": "3bfbfade-e6b6-4b9e-ad83-25fad6fd8b8d",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "08e5f130-5c37-4972-8b26-a4a3a61db59f",
                    "equipmentType": "bus",
                    "mrid": "ecf62195-39b2-4f18-8f25-83edf0659c39",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "f8a82991-14b9-43b9-95b9-ebd013dee1d0"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "cd17f51d-89af-4740-b9c7-376701cb9d28",
                    "equipmentType": "busbar",
                    "mrid": "c95d6593-30bf-49f2-b7f3-6ed4a30f4f70",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "862aebd7-c70b-45d6-a4f8-2b4acf3f8e4e",
                    "equipmentType": "transformer",
                    "mrid": "726c6f06-969d-444b-9012-64a0083fc81c",
                    "name": "Equipment 2"
                }
            ],
            "groupCode": "46540ae9-c0b4-486a-801c-05920763bf12"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10Y1001A1001A82H",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "35d74ef0-0585-416e-a06d-991141d93ca1",
                    "equipmentType": "switch",
                    "mrid": "47ac1d45-5bd1-43f4-bfee-4b315d3fecc3",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "9bca28ad-83cf-4095-b0c2-681c26eafee7"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "environmental",
            "contingencyType": "ordinary",
            "description": null,
            "equipmentOperatorCode": "650cd691-cd99-46bb-b9a4-62bb63c3ff85",
            "groupCode": "f8a82991-14b9-43b9-95b9-ebd013dee1d0",
            "mrid": "d5dc2e17-0b72-427b-857c-521b2c809665",
            "mustStudy": true,
            "name": "Contingency 1",
            "probability": 43.72
        },
        {
            "contingencyCondition": "operation",
            "contingencyType": "ordinary",
            "description": null,
            "equipmentOperatorCode": "1d9756a2-b824-4229-9e9d-9d4920b0bb0e",
            "groupCode": "46540ae9-c0b4-486a-801c-05920763bf12",
            "mrid": "15252d5b-5e61-4d0d-8fa6-4e32d43926de",
            "mustStudy": false,
            "name": null,
            "probability": null
        },
        {
            "contingencyCondition": null,
            "contingencyType": "exceptional",
            "description": null,
            "equipmentOperatorCode": "bf2a7ee3-cae7-4083-9168-0558289d000c",
            "groupCode": "9bca28ad-83cf-4095-b0c2-681c26eafee7",
            "mrid": "146f09dc-7350-499b-abfe-3a268d98c6f9",
            "mustStudy": true,
            "name": "Contingency 3",
            "probability": null
        }
    ],
    "contingencyListId": "cd00c5a6-ab72-4376-b032-85abedfd37ea",
    "documentId": "47b291e1-9bd0-43b4-bb43-2ebb10630845",
    "gridModelId": "8fb26753-a5e1-45ba-a393-9b93885c9cab",
    "ownerCode": "10XDE-ENBW--TNGX",
    "ownerRole": "Grid Manager",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-02T00:00:00",
        "to": "2025-01-02T01:00:00"
    },
    "version": 7
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_3.json
{
    "businessTimestamp": "2024-01-03T00:05:47",
    "cdsId": "495d01b0-6757-42f3-a0db-bdce57a6a09e",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YDE-ENBW-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "f07e7cae-3fcb-451e-992c-bdc8ff21c160",
                    "equipmentType": "line",
                    "mrid": "0d0a7810-7b96-4ac4-91ce-4ff1171209ed",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "0018ef33-fb14-445e-858b-53ca0677852c"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YDE-ENBW-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "50aba42e-d02b-45bb-bf3b-82f6e6a72696",
                    "equipmentType": "load",
                    "mrid": "3acc242a-6a72-42b9-a91b-8426c5fce89f",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YDE-ENBW-----N",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "620b553c-a09b-43f3-808c-44c93a846293",
                    "equipmentType": "bus",
                    "mrid": "fb2d5f9a-2b31-43b8-9d91-a53a738b44ae",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YDE-ENBW-----N",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "e11b7382-ab94-49cb-a038-17e9f56bd757",
                    "equipmentType": "gen",
                    "mrid": "1735564f-0abe-4bcc-b9e8-79fd641e4680",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "d0afe627-07ba-4176-b3aa-0586de7cb4d7"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YDE-ENBW-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "0704967b-de16-4deb-a34f-38080fc96a49",
                    "equipmentType": "gen",
                    "mrid": "81c1a333-e26f-4c3a-a0b8-dbb4784c62c2",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "8aaac9e5-54a6-46a6-841f-b89f44f62ffd"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "design",
            "contingencyType": "exceptional",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "f5a86980-9ac7-4727-b56f-bae494b740b3",
            "groupCode": "01f76aca-a794-468f-b494-151756e29612",
            "mrid": "f32e0077-caa9-4be7-9b2c-31b5f88a58d6",
            "mustStudy": true,
            "name": null,
            "probability": 52.36
        },
        {
            "contingencyCondition": "operation",
            "contingencyType": "outOfRange",
            "description": null,
            "equipmentOperatorCode": "8a29f768-27a3-41d0-b5bb-140bc689ceef",
            "groupCode": "8e87ecff-c581-4579-81c4-0cdb1808b0e2",
            "mrid": "910b782d-2ddd-4555-b611-69a949c3b4a1",
            "mustStudy": false,
            "name": "Contingency 2",
            "probability": 85.75
        }
    ],
    "contingencyListId": "0a7d44af-c239-486b-8e0f-3d021f9b0b40",
    "documentId": "097ae456-17a9-418e-acf6-161d27eb4b2f",
    "gridModelId": "bc1e5a93-045e-478e-afc4-d0054bcc01f2",
    "ownerCode": "10XDE-ENBW--TNGX",
    "ownerRole": "System Operator",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-03T00:00:00",
        "to": "2024-01-03T04:00:00"
    },
    "version": 6
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_4.json
{
    "businessTimestamp": "2024-01-04T00:10:35",
    "cdsId": "dc7b63c7-1fc1-4f3b-b951-19b3bed8d38d",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YDE-VE-------2",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "72a5830e-e377-4431-99b0-c4e69169bf34",
                    "equipmentType": "bus",
                    "mrid": "7f4951f8-f248-41d6-aef6-8a7ce220de90",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YDE-VE-------2",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "321d93a5-2b4d-4513-8ddf-95853c21d4ac",
                    "equipmentType": "bus",
                    "mrid": "25977b55-4ccc-486e-a48c-c267be7615d6",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YDE-VE-------2",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "452be186-60cc-4593-a2af-2310de210a8b",
                    "equipmentType": "switch",
                    "mrid": "0392692f-faf0-4deb-8806-2a6d2fe99cc6",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "008320de-f03d-42ff-a261-fbe94c3b6549"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "outOfRange",
            "description": null,
            "equipmentOperatorCode": "f6f39066-fa5e-4164-b934-919bcfde75c8",
            "groupCode": "5e947e8d-5529-481b-b548-5de1175ccf00",
            "mrid": "3ae9daa8-88ae-4b70-9837-de535cb32cd4",
            "mustStudy": true,
            "name": null,
            "probability": 44.56
        },
        {
            "contingencyCondition": null,
            "contingencyType": "ordinary",
            "description": null,
            "equipmentOperatorCode": "6b32b3ed-3b02-4fcf-9fb9-b4ca07a0fec2",
            "groupCode": "e36b04ab-3d18-496c-a328-3d9355fd07dd",
            "mrid": "3ab150e4-bf58-4258-8bee-a1fdf261ed3b",
            "mustStudy": true,
            "name": null,
            "probability": 74.59
        },
        {
            "contingencyCondition": "environmental",
            "contingencyType": "outOfRange",
            "description": null,
            "equipmentOperatorCode": "5e6671f6-1784-40e1-8da6-7975ac094a54",
            "groupCode": "c9c8892c-38d3-4fff-82dd-82a5e30964a0",
            "mrid": "ab709a39-0827-4062-a8e1-4c648bd1e54d",
            "mustStudy": false,
            "name": "Contingency 3",
            "probability": null
        }
    ],
    "contingencyListId": "75375f75-dae8-477d-9dd6-9ce157d791bb",
    "documentId": "ffb06f3c-4c01-4163-b6c9-58c2cc30b038",
    "gridModelId": "7674426c-6b44-4aa2-8b6d-726148733080",
    "ownerCode": "10YDE-VE-------2",
    "ownerRole": "Network Engineer",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-04T00:00:00",
        "to": "2024-01-04T01:00:00"
    },
    "version": 7
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/CO_flatlist/CO_Flat_List_Schema_fixed_2.json
{
    "businessTimestamp": "2024-01-02T01:55:35",
    "cdsId": "9a4ad2e0-fe76-4fd3-b8de-6f616804af8b",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YCB-BE-------T",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "7b477b43-e374-422f-8778-2781373277c1",
                    "equipmentType": "switch",
                    "mrid": "d1968494-3ed8-4ecd-805a-54aa8f3172c4",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "7036878b-3e6b-4a3c-9c66-bd6204b6e0a2"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YCB-BE-------T",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "2a4a2666-d4b0-449b-8982-7ae4c408fa42",
                    "equipmentType": "shuntCompensator",
                    "mrid": "81a4a388-7123-4772-91e7-4b0312c71711",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "b4e9df62-7f88-4a62-a93f-a89f225e3b6a"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": "design",
            "contingencyType": "ordinary",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "e32d9077-1ee0-41df-999e-d6b2b4d0cef6",
            "groupCode": "dec10e3f-80ca-40b4-9d89-a17504da382f",
            "mrid": "f218925c-c803-4e01-8ffc-22f0da066871",
            "mustStudy": true,
            "name": null,
            "probability": 13.59
        },
        {
            "contingencyCondition": "operation",
            "contingencyType": "exceptional",
            "description": null,
            "equipmentOperatorCode": "5d160ca9-1f34-4446-a4de-613f22f97e1a",
            "groupCode": "2e03620d-53b1-407c-bd30-3ac50d1df086",
            "mrid": "c5496f8c-0cd7-4b34-b836-07581bbe49b6",
            "mustStudy": true,
            "name": "Contingency 2",
            "probability": null
        }
    ],
    "contingencyListId": "41792e7b-3294-48cb-aff1-98b359d005e7",
    "documentId": "78718d22-8ed1-4082-8e5e-a4c8612c792e",
    "gridModelId": "4c70571d-a96a-41fa-bb5a-c74174d3cb6c",
    "ownerCode": "10X1001A1001A094",
    "ownerRole": "System Operator",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2024-01-02T00:00:00",
        "to": "2024-01-02T16:00:00"
    },
    "version": 9
}

=== arielmbomakaeyros/como-files/combined_aeco_co_flatlist/combined_sample_data/aeco_co_flatlist/CO_Flat_List_Schema_fixed_3.json
{
    "businessTimestamp": "2025-01-03T00:30:00",
    "cdsId": "481bfe63-28eb-4256-925c-df4c419c8f1c",
    "comoDocumentType": "INTERNAL_CO_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "contingencyGroupList": [
        {
            "equipmentList": [
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "d5d9a622-87b8-4f6a-a58c-8d8ba65110f9",
                    "equipmentType": "line",
                    "mrid": "bb847dc8-1777-44ed-a339-87284beab7e4",
                    "name": "Equipment 1"
                }
            ],
            "groupCode": "ee15651e-1218-4a9a-bc33-b5310116ae9d"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "646723ec-cdc7-45d7-b749-025cb4f86963",
                    "equipmentType": "line",
                    "mrid": "3149afe1-47dc-4528-a3df-72c5862d76f4",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "dd117e48-1c56-4bff-b547-0810233ee48d",
                    "equipmentType": "busbar",
                    "mrid": "75283b89-8272-4399-81fd-26a5c438e137",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "077d5cee-4814-4dfd-b7d6-ffa4d36442c4",
                    "equipmentType": "load",
                    "mrid": "72b057fb-953d-4d51-b9dc-2effe139ec8a",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "4ef98902-c99f-40ec-9060-1529504145cc"
        },
        {
            "equipmentList": [
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 1",
                    "equipmentMrid": "0782d1c7-54bf-4bac-a433-3fc716f99126",
                    "equipmentType": "load",
                    "mrid": "e86dd618-c551-4a3c-9359-73ab5247b32a",
                    "name": "Equipment 1"
                },
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 2",
                    "equipmentMrid": "05aa5cbe-8089-4e73-9a06-b0a56a0e5fe1",
                    "equipmentType": "gen",
                    "mrid": "2095855c-7d29-4e2d-abfb-32a5a76ccaf5",
                    "name": "Equipment 2"
                },
                {
                    "areaCode": "10YCZ-CEPS-----N",
                    "description": "Sample equipment description 3",
                    "equipmentMrid": "442264d6-e0bc-4409-a8c9-251489710538",
                    "equipmentType": "busbar",
                    "mrid": "ee8df83a-8185-4f40-928f-810be06f7a5e",
                    "name": "Equipment 3"
                }
            ],
            "groupCode": "99f88275-e896-44fe-bac0-539f7a8157e8"
        }
    ],
    "contingencyList": [
        {
            "contingencyCondition": null,
            "contingencyType": "exceptional",
            "description": "Sample contingency description 1",
            "equipmentOperatorCode": "56edc149-a2a0-4973-8028-3df36a00a81e",
            "groupCode": "ee15651e-1218-4a9a-bc33-b5310116ae9d",
            "mrid": "b544b518-a9f1-4433-9b11-e5f08ec45490",
            "mustStudy": true,
            "name": "Contingency 1",
            "probability": 12.91
        },
        {
            "contingencyCondition": null,
            "contingencyType": "ordinary",
            "description": "Sample contingency description 2",
            "equipmentOperatorCode": "681c7e27-7b6a-4ed5-b2ca-59bda5063b75",
            "groupCode": "4ef98902-c99f-40ec-9060-1529504145cc",
            "mrid": "2978dfa1-8c62-4fec-a16b-b1088b03139a",
            "mustStudy": true,
            "name": null,
            "probability": 90.5
        },
        {
            "contingencyCondition": "geographicalLocation",
            "contingencyType": "ordinary",
            "description": "Sample contingency description 3",
            "equipmentOperatorCode": "9b3a37a3-1d11-44d2-a196-c913ed33155d",
            "groupCode": "99f88275-e896-44fe-bac0-539f7a8157e8",
            "mrid": "86ef6771-6fd5-4978-9fc7-59518225a4e6",
            "mustStudy": false,
            "name": null,
            "probability": 49.88
        }
    ],
    "contingencyListId": "4df46a82-93fa-4f69-ad1f-eaa431b3f2a6",
    "documentId": "0a70ebe6-7934-4f2b-a6e5-9c35e869439d",
    "gridModelId": "4ceec59b-cece-46d5-8a31-7301c4497f6a",
    "ownerCode": "10XCZ-CEPS-GRIDE",
    "ownerRole": "System Operator",
    "timeHorizon": "dayAhead",
    "timeInterval": {
        "from": "2025-01-03T00:00:00",
        "to": "2025-01-03T01:00:00"
    },
    "version": 7
}
