=== arielmbomakaeyros/como-files/flat_list_psk/schema/Psk_Flat_List_Specification_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/Psk_Flat_List_Specification",
    "title": "PskFlatList",
    "type": "object",
    "properties": {
        "businessTimestamp": {
            "type": [
                "string",
                "null"
            ]
        },
        "cdsId": {
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "documentId": {
            "type": "string"
        },
        "ownerCode": {
            "type": "string"
        },
        "ownerRole": {
            "type": "string"
        },
        "powerShiftKeyList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PowerShiftKey"
            }
        },
        "timeHorizon": {
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "timeInterval": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "#/definitions/TimeInterval"
                }
            ]
        },
        "version": {
            "type": "integer"
        }
    },
    "definitions": {
        "BlockType": {
            "description": "Kind of generating and load shift keys strategy.\n",
            "type": "string",
            "enum": [
                "consumptionsFlat",
                "consumptionsP",
                "explicitDistribution",
                "explicitInstruction",
                "generatorsAndConsumptionsP",
                "generatorsFlat",
                "generatorsP",
                "generatorsPmax",
                "generatorsPmin",
                "generatorsPriority",
                "generatorsRemainingCapacity",
                "generatorsUsedCapacity",
                "nonConformLoadP",
                "storageFlat",
                "storageP"
            ]
        },
        "DocumentTypeKind": {
            "type": "string",
            "const": "INTERNAL_PSK_FLAT_LIST"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "PowerShiftKey": {
            "type": "object",
            "properties": {
                "areaCode": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "blockType": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/BlockType"
                        }
                    ]
                },
                "energyGroupMrid": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "resourceMrid": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "resourceType": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ResourceType"
                        }
                    ]
                },
                "value": {
                    "$ref": "#/definitions/PowerShiftKeyValue"
                }
            },
            "additionalProperties": true,
            "required": [
                "value"
            ]
        },
        "PowerShiftKeyValue": {
            "type": "object",
            "properties": {
                "activePowerMax": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "activePowerMin": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "blockOrder": {
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "participationFactor": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "shiftDirection": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ShiftDirection"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "required": []
        },
        "ResourceType": {
            "type": "string",
            "enum": [
                "energyConsumer",
                "energyGroup",
                "generatingUnit",
                "hydroPump",
                "powerElectronicsUnit"
            ]
        },
        "ShiftDirection": {
            "type": "string",
            "enum": [
                "down",
                "up",
                "upAndDown"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "TimeInterval": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "format": "date-time"
                },
                "to": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "required": [
                "from",
                "to"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "cdsId",
        "comoDocumentType",
        "comoDocumentVersion",
        "documentId",
        "ownerCode",
        "ownerRole",
        "timeHorizon",
        "version"
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_10.json
{
    "businessTimestamp": "2024-01-01T09:30:00",
    "timeInterval": {
        "from": "2024-01-01T09:00:00",
        "to": "2024-01-01T10:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10XSI-ELES-----1",
    "ownerRole": "System Operator",
    "cdsId": "46ce52e6-4e0a-4219-a80f-9ec191938d43",
    "documentId": "9baa18e3-f45c-4144-8f17-dbf4c0f483ec",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YSI-ELES-----O",
            "blockType": "consumptionsP",
            "energyGroupMrid": "9a41a5f3-14b2-463f-8ed8-cd174b86ce69",
            "resourceMrid": "1e30ab3d-135c-49bf-a512-48f4ad4fed08",
            "resourceType": "generatingUnit",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": 1,
                "participationFactor": 56.06,
                "shiftDirection": "down"
            }
        }
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_4.json
{
    "businessTimestamp": "2024-01-01T03:30:00",
    "timeInterval": {
        "from": "2024-01-01T03:00:00",
        "to": "2024-01-01T04:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10X1001A1001A329",
    "ownerRole": "System Operator",
    "cdsId": "39a2aaba-6950-4fb3-a0ce-2873b0c687b5",
    "documentId": "dfa80842-abd3-4b1e-8093-7a2741caacbf",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YHU-MAVIR----U",
            "blockType": "storageP",
            "energyGroupMrid": "eb3c6fbd-434b-46dd-96e4-6080b7ca298b",
            "resourceMrid": "333338a9-f34b-49dc-907a-0912eee336f9",
            "resourceType": "powerElectronicsUnit",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": 1,
                "participationFactor": 75.68,
                "shiftDirection": "up"
            }
        },
        {
            "areaCode": "10YHU-MAVIR----U",
            "blockType": "generatorsAndConsumptionsP",
            "energyGroupMrid": "1b9c06a6-21f8-4b9a-b47f-00bdd3721049",
            "resourceMrid": "9238ffcf-fa49-41a0-a59a-f0000844e73b",
            "resourceType": "hydroPump",
            "value": {
                "activePowerMax": 140.19,
                "activePowerMin": 41.11,
                "blockOrder": 2,
                "participationFactor": 84.66,
                "shiftDirection": "upAndDown"
            }
        }
    ]
}
