=== arielmbomakaeyros/como-files/flat_list_psk/schema/Psk_Flat_List_Specification_fixed.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://iec.ch/TC57/Psk_Flat_List_Specification",
    "title": "PskFlatList",
    "type": "object",
    "properties": {
        "businessTimestamp": {
            "type": [
                "string",
                "null"
            ]
        },
        "cdsId": {
            "type": "string"
        },
        "comoDocumentType": {
            "$ref": "#/definitions/DocumentTypeKind"
        },
        "comoDocumentVersion": {
            "$ref": "#/definitions/DocumentVersionKind"
        },
        "documentId": {
            "type": "string"
        },
        "ownerCode": {
            "type": "string"
        },
        "ownerRole": {
            "type": "string"
        },
        "powerShiftKeyList": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/PowerShiftKey"
            }
        },
        "timeHorizon": {
            "$ref": "#/definitions/TimeHorizonKind"
        },
        "timeInterval": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "#/definitions/TimeInterval"
                }
            ]
        },
        "version": {
            "type": "integer"
        }
    },
    "definitions": {
        "BlockType": {
            "description": "Kind of generating and load shift keys strategy.\n",
            "type": "string",
            "enum": [
                "consumptionsFlat",
                "consumptionsP",
                "explicitDistribution",
                "explicitInstruction",
                "generatorsAndConsumptionsP",
                "generatorsFlat",
                "generatorsP",
                "generatorsPmax",
                "generatorsPmin",
                "generatorsPriority",
                "generatorsRemainingCapacity",
                "generatorsUsedCapacity",
                "nonConformLoadP",
                "storageFlat",
                "storageP"
            ]
        },
        "DocumentTypeKind": {
            "type": "string",
            "const": "INTERNAL_PSK_FLAT_LIST"
        },
        "DocumentVersionKind": {
            "type": "string",
            "const": "R24Q4V1_0"
        },
        "PowerShiftKey": {
            "type": "object",
            "properties": {
                "areaCode": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "blockType": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/BlockType"
                        }
                    ]
                },
                "energyGroupMrid": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "resourceMrid": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "resourceType": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ResourceType"
                        }
                    ]
                },
                "value": {
                    "$ref": "#/definitions/PowerShiftKeyValue"
                }
            },
            "additionalProperties": true,
            "required": [
                "value"
            ]
        },
        "PowerShiftKeyValue": {
            "type": "object",
            "properties": {
                "activePowerMax": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "activePowerMin": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "blockOrder": {
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "participationFactor": {
                    "type": [
                        "number",
                        "null"
                    ]
                },
                "shiftDirection": {
                    "oneOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/ShiftDirection"
                        }
                    ]
                }
            },
            "additionalProperties": true,
            "required": []
        },
        "ResourceType": {
            "type": "string",
            "enum": [
                "energyConsumer",
                "energyGroup",
                "generatingUnit",
                "hydroPump",
                "powerElectronicsUnit"
            ]
        },
        "ShiftDirection": {
            "type": "string",
            "enum": [
                "down",
                "up",
                "upAndDown"
            ]
        },
        "TimeHorizonKind": {
            "description": "The code list of the time horizons",
            "type": "string",
            "enum": [
                "dayAhead",
                "intraday",
                "monthAhead",
                "twoDaysAhead",
                "weekAhead",
                "yearAhead"
            ]
        },
        "TimeInterval": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "format": "date-time"
                },
                "to": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "required": [
                "from",
                "to"
            ]
        }
    },
    "additionalProperties": true,
    "required": [
        "cdsId",
        "comoDocumentType",
        "comoDocumentVersion",
        "documentId",
        "ownerCode",
        "ownerRole",
        "timeHorizon",
        "version"
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_1.json
{
    "businessTimestamp": null,
    "cdsId": "b45a52c7-0346-4ebd-801b-ab7b1610ac04",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "documentId": "93573d27-6972-4a36-8d2d-7090d79b437e",
    "ownerCode": "10XDE-EON-NETZ-C",
    "ownerRole": "Network Engineer",
    "powerShiftKeyList": [
        {
            "areaCode": "10YDOM-1010A0213",
            "blockType": null,
            "energyGroupMrid": null,
            "resourceMrid": null,
            "resourceType": "hydroPump",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": null,
                "participationFactor": null,
                "shiftDirection": null
            }
        }
    ],
    "timeHorizon": "monthAhead",
    "timeInterval": {
        "from": "2024-01-01T00:00:00",
        "to": "2024-01-01T06:00:00"
    },
    "version": 9
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_7.json
{
    "businessTimestamp": null,
    "cdsId": "ce3255af-4b1e-46f8-b09c-1bc9763b6cbd",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "documentId": "54797d72-90e0-47c0-8fad-7fbc1965fe5a",
    "ownerCode": "10YDE-VE-------2",
    "ownerRole": "System Operator",
    "powerShiftKeyList": null,
    "timeHorizon": "monthAhead",
    "timeInterval": null,
    "version": 7
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_3.json
{
    "businessTimestamp": "2024-01-01T02:30:00",
    "timeInterval": {
        "from": "2024-01-01T02:00:00",
        "to": "2024-01-01T03:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10XAT-APG------Z",
    "ownerRole": "Grid Manager",
    "cdsId": "8cfccce3-00d3-4565-b50b-eedfaa7b4534",
    "documentId": "c00e7996-9978-408e-911a-f9f33cd04838",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YAT-APG------L",
            "blockType": "generatorsAndConsumptionsP",
            "energyGroupMrid": "a5381ffb-26f8-4361-85dd-603bf733e72c",
            "resourceMrid": "550b17b2-280d-4a83-a8fb-04286225c12f",
            "resourceType": "hydroPump",
            "value": {
                "activePowerMax": 64.85,
                "activePowerMin": 54.88,
                "blockOrder": 1,
                "participationFactor": 95.97,
                "shiftDirection": "up"
            }
        }
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_2.json
{
    "businessTimestamp": "2025-02-22T05:57:38.551734",
    "cdsId": "0e22139a-9c63-4962-85c6-5b013d5272bd",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "documentId": "0b1f8281-c2c7-458e-ac69-9520dc8feb08",
    "ownerCode": "10XDE-ENBW--TNGX",
    "ownerRole": "Network Engineer",
    "powerShiftKeyList": null,
    "timeHorizon": "twoDaysAhead",
    "timeInterval": null,
    "version": 6
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_6.json
{
    "businessTimestamp": "2024-01-01T05:30:00",
    "timeInterval": {
        "from": "2024-01-01T05:00:00",
        "to": "2024-01-01T06:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10X1001A1001A094",
    "ownerRole": "System Operator",
    "cdsId": "4ba0254d-937e-48b6-b0c2-dbff17106c84",
    "documentId": "0a26b6a2-4347-47c4-80e3-c9cebc083cd8",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YBE----------2",
            "blockType": "explicitDistribution",
            "energyGroupMrid": "032ead8a-2424-41f7-b713-86bb656215e8",
            "resourceMrid": "4a0f239e-974b-4d76-9a66-b679178d5419",
            "resourceType": "hydroPump",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": 1,
                "participationFactor": 75.87,
                "shiftDirection": "upAndDown"
            }
        }
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_5.json
{
    "businessTimestamp": "2025-02-19T05:57:38.552206",
    "cdsId": "190e0ad2-1f69-43ba-bacb-71a9d936b586",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "documentId": "6bbcb5db-754a-4ae8-b04f-3ef941c87e76",
    "ownerCode": "10XDE-ENBW--TNGX",
    "ownerRole": "Grid Manager",
    "powerShiftKeyList": [
        {
            "areaCode": "763a5d64-afa8-43ab-a5cb-b6bf0cf79d14",
            "blockType": null,
            "energyGroupMrid": "f28cb7aa-cb17-463b-a5e6-179ddf7428f0",
            "resourceMrid": "d5adeefa-f82a-4ea5-8261-0d6ef7779831",
            "resourceType": null,
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": null,
                "participationFactor": null,
                "shiftDirection": null
            }
        }
    ],
    "timeHorizon": "twoDaysAhead",
    "timeInterval": {
        "from": "2024-01-05T00:00:00",
        "to": "2024-01-05T10:00:00"
    },
    "version": 5
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_8.json
{
    "businessTimestamp": "2024-01-01T07:30:00",
    "timeInterval": {
        "from": "2024-01-01T07:00:00",
        "to": "2024-01-01T08:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10XPL-TSO------P",
    "ownerRole": "System Operator",
    "cdsId": "14678e9a-305b-4cd0-a12f-ff7ed5805e64",
    "documentId": "82f1b5fb-9179-4822-b2ef-edd4432d7066",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YPL-AREA-----S",
            "blockType": "storageFlat",
            "energyGroupMrid": "1ad09ba9-34fc-4aac-a015-fc51577529af",
            "resourceMrid": "55f59937-c4d1-4b9b-b647-e04772c30676",
            "resourceType": "generatingUnit",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": 1,
                "participationFactor": 13.23,
                "shiftDirection": "upAndDown"
            }
        },
        {
            "areaCode": "10YPL-AREA-----S",
            "blockType": "generatorsRemainingCapacity",
            "energyGroupMrid": "fb421e19-905d-4e06-b7d4-123ff61374d4",
            "resourceMrid": "e644bfaf-0a79-4986-8e51-688727c9210c",
            "resourceType": "energyConsumer",
            "value": {
                "activePowerMax": 138.96,
                "activePowerMin": 69.41,
                "blockOrder": 2,
                "participationFactor": 27.04,
                "shiftDirection": "up"
            }
        },
        {
            "areaCode": "10YPL-AREA-----S",
            "blockType": "explicitInstruction",
            "energyGroupMrid": "8d7b1f41-799a-4f7b-8656-6dc0ab53f912",
            "resourceMrid": "58586d6c-847b-4529-9c3d-0c0fe744b6e0",
            "resourceType": "energyConsumer",
            "value": {
                "activePowerMax": null,
                "activePowerMin": null,
                "blockOrder": 3,
                "participationFactor": 88.87,
                "shiftDirection": "upAndDown"
            }
        }
    ]
}

=== arielmbomakaeyros/como-files/flat_list_psk/Psk_Flat_List_Specification_fixed_sample_data/Psk_Flat_List_Specification_fixed_file_9.json
{
    "businessTimestamp": "2024-01-01T08:30:00",
    "timeInterval": {
        "from": "2024-01-01T08:00:00",
        "to": "2024-01-01T09:00:00"
    },
    "version": 1,
    "timeHorizon": "dayAhead",
    "ownerCode": "10XHR-HEP-OPS--A",
    "ownerRole": "Grid Manager",
    "cdsId": "b009f515-1b50-4b58-adf1-a560721145ab",
    "documentId": "a56405a4-d089-4fef-95cf-e99cb870266b",
    "comoDocumentType": "INTERNAL_PSK_FLAT_LIST",
    "comoDocumentVersion": "R24Q4V1_0",
    "powerShiftKeyList": [
        {
            "areaCode": "10YHR-HEP------M",
            "blockType": "generatorsPmin",
            "energyGroupMrid": "54709288-8905-4334-b729-9e133b617bf4",
            "resourceMrid": "432605d1-4486-4628-8f93-5cb9f5b88a2a",
            "resourceType": "energyConsumer",
            "value": {
                "activePowerMax": 159.61,
                "activePowerMin": 99.76,
                "blockOrder": 1,
                "participationFactor": 43.4,
                "shiftDirection": "up"
            }
        }
    ]
}
